import { installingWorldPlazaDocumentElementFromPointFiniteCoordinateGuard } from '@/components/world/domains/installingWorldPlazaDocumentElementFromPointFiniteCoordinateGuard';

installingWorldPlazaDocumentElementFromPointFiniteCoordinateGuard();
