import type { DefiningWorldPlazaBiomeKind } from '@/components/world/domains/definingWorldPlazaBiomeKind';

/**
 * Lore-toned word pools for permanent biome region names.
 *
 * Wanderer voice: concrete place names, not high-fantasy pomp. Shared adjectives
 * mix with per-biome nouns so each region cell can resolve a unique label.
 *
 * @module components/world/domains/definingWorldPlazaBiomeRegionNameWordPools
 */

/** Shared adjectives used across all biome kinds. */
export const DEFINING_WORLD_PLAZA_BIOME_REGION_NAME_SHARED_ADJECTIVES =
  [
    'Quiet',
    'Old',
    'Far',
    'Low',
    'High',
    'Broken',
    'Hollow',
    'Pale',
    'Ashen',
    'Still',
    'Windy',
    'Sunlit',
    'Shaded',
    'Crooked',
    'Narrow',
    'Wide',
    'Forgotten',
    'Hidden',
    'Rough',
    'Soft',
    'Bitter',
    'Gentle',
    'Lonely',
    'Crowded',
    'Dusty',
    'Damp',
    'Bright',
    'Dim',
    'Scarred',
    'Untrod',
  ] as const;

/** Per-biome noun pools (Corpus place-name flavor). */
export const DEFINING_WORLD_PLAZA_BIOME_REGION_NAME_NOUNS_BY_KIND: Record<
  DefiningWorldPlazaBiomeKind,
  readonly string[]
> = {
  plains: [
    'Meadow',
    'Pasture',
    'Grassreach',
    'Herdfield',
    'Openfold',
    'Windflat',
    'Claimsteppe',
    'Wanderlea',
    'Softmarch',
    'Greenbench',
    'Cowtrail',
    'Sheepfold',
  ],
  forest: [
    'Timberline',
    'Shadewood',
    'Needledeep',
    'Wolftrack',
    'Canopy',
    'Rootbend',
    'Mossbank',
    'Quietgrove',
    'Trunkward',
    'Leafdark',
    'Branchfall',
    'Underwood',
  ],
  flower_forest: [
    'Bloomvale',
    'Petalreach',
    'Colorlea',
    'Honeybend',
    'Brightmead',
    'Softpetal',
    'Gardenfold',
    'Pollenflat',
    'Roseward',
    'Lilymarch',
    'Bloomstep',
    'Petalbank',
  ],
  jungle: [
    'Canopydeep',
    'Vinewall',
    'Hotshade',
    'Monkeycall',
    'Tigertrack',
    'Fruitfall',
    'Wetgreen',
    'Rootmaze',
    'Leafstorm',
    'Undergrowth',
    'Steamgrove',
    'Jaguarpath',
  ],
  desert: [
    'Dune',
    'Scorchflat',
    'Sandreach',
    'Drymarch',
    'Heatglass',
    'Bonewash',
    'Miragefold',
    'Ashdune',
    'Sunbake',
    'Dustbowl',
    'Saltflat',
    'Thirstline',
  ],
  snowy_plains: [
    'Frostlea',
    'Whiteflat',
    'Icewind',
    'Snowreach',
    'Coldmarch',
    'Huskypath',
    'Frozenfold',
    'Palebench',
    'Rimefield',
    'Stillice',
    'Winterstep',
    'Bitterlea',
  ],
  swamp: [
    'Mire',
    'Reedbank',
    'Murkpool',
    'Lilyflat',
    'Crocwater',
    'Softbog',
    'Fogreach',
    'Stillmire',
    'Mosswater',
    'Siltbend',
    'Quietbog',
    'Wetshadow',
  ],
  savanna: [
    'Grasssea',
    'Acaciaflat',
    'Pridepath',
    'Drylea',
    'Zebratrack',
    'Sunsteppe',
    'Lionfold',
    'Tallgrass',
    'Heatlea',
    'Openpride',
    'Dustmarch',
    'Herdsea',
  ],
  badlands: [
    'Claydrop',
    'Redledge',
    'Steepwash',
    'Layerhill',
    'Scarcliff',
    'Drycanyon',
    'Rustbench',
    'Fallline',
    'Clayreach',
    'Redmarch',
    'Isolfold',
    'Viewdrop',
  ],
  beach: [
    'Shore',
    'Sandbar',
    'Tideline',
    'Driftflat',
    'Shellbank',
    'Neutralshore',
    'Wavebend',
    'Saltstep',
    'Foamlea',
    'Coastfold',
    'Quietbeach',
    'Softshore',
  ],
  ocean: [
    'Deepwater',
    'Farwave',
    'Rimsea',
    'Openbrine',
    'No-shore',
    'Blueflat',
    'Saltreach',
    'Horizon',
    'Stillbrine',
    'Waveglass',
    'Farbrine',
    'Endless',
  ],
  rocky: [
    'Quarry',
    'Stoneflat',
    'Bareledge',
    'Rockfold',
    'Hardbench',
    'Cliffward',
    'Gravelreach',
    'Stonepath',
    'Baremarch',
    'Fortrock',
    'Crag',
    'Slabfield',
  ],
  firelands: [
    'Emberflat',
    'Ashreach',
    'Forgevent',
    'Scorchbank',
    'Ruinheat',
    'Cinderfold',
    'Ashmarch',
    'Heatglass',
    'Forgewright',
    'Emberledge',
    'Burnstep',
    'Ashcliff',
  ],
};

/** Optional connectors for "The X of Y" style names. */
export const DEFINING_WORLD_PLAZA_BIOME_REGION_NAME_CONNECTORS = [
  'of',
  'at',
  'beyond',
] as const;
