/**
 * Per-skin avatar character definitions for the local plaza player.
 *
 * Each definition bundles everything the avatar tick needs that differs between
 * skins: the texture loader, its TanStack Query key, the motion sheet layouts,
 * per-motion frame rates, and rendering tuning (anchor, scale, default facing).
 *
 * Movement physics (jump distance, arc height, jump/fall timing) stay shared
 * across skins, so only presentation varies when switching the local avatar.
 *
 * @module components/world/domains/definingWorldPlazaAvatarCharacterDefinition
 */

import {
  DEFINING_WORLD_PLAZA_AVATAR_SKIN,
  DEFINING_WORLD_PLAZA_AVATAR_SKIN_DEFAULT,
  type DefiningWorldPlazaAvatarSkinId,
} from "@/components/world/domains/definingWorldPlazaAvatarSkinConstants";
import {
  DEFINING_WORLD_PLAZA_GIRL_SAMPLE_FALL_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_GIRL_SAMPLE_FALL_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_GIRL_SAMPLE_FALL_SPRITE_DIRECTION,
} from "@/components/world/domains/definingWorldPlazaGirlSampleFallConstants";
import {
  DEFINING_WORLD_PLAZA_GIRL_SAMPLE_IDLE_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_GIRL_SAMPLE_IDLE_MOTION_SHEET_LAYOUT,
} from "@/components/world/domains/definingWorldPlazaGirlSampleIdleConstants";
import {
  DEFINING_WORLD_PLAZA_GIRL_SAMPLE_JUMP_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_GIRL_SAMPLE_JUMP_MOTION_SHEET_LAYOUT,
} from "@/components/world/domains/definingWorldPlazaGirlSampleJumpConstants";
import {
  DEFINING_WORLD_PLAZA_GIRL_SAMPLE_CHARACTER_TEXTURES_QUERY_KEY,
  DEFINING_WORLD_PLAZA_GIRL_SAMPLE_RUN_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_GIRL_SAMPLE_RUN_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_GIRL_SAMPLE_WALK_ANCHOR_X_NORMALIZED,
  DEFINING_WORLD_PLAZA_GIRL_SAMPLE_WALK_ANCHOR_Y_NORMALIZED,
  DEFINING_WORLD_PLAZA_GIRL_SAMPLE_WALK_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_GIRL_SAMPLE_WALK_DEFAULT_DIRECTION,
  DEFINING_WORLD_PLAZA_GIRL_SAMPLE_WALK_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_GIRL_SAMPLE_WALK_SPRITE_SCALE,
  type DefiningWorldPlazaGirlSampleMotionSheetLayout,
  type DefiningWorldPlazaGirlSampleWalkDirection,
} from "@/components/world/domains/definingWorldPlazaGirlSampleWalkConstants";
import {
  DEFINING_WORLD_PLAZA_HUSKY_ANCHOR_X_NORMALIZED,
  DEFINING_WORLD_PLAZA_HUSKY_ANCHOR_Y_NORMALIZED,
  DEFINING_WORLD_PLAZA_HUSKY_CHARACTER_TEXTURES_QUERY_KEY,
  DEFINING_WORLD_PLAZA_HUSKY_DEFAULT_DIRECTION,
  DEFINING_WORLD_PLAZA_HUSKY_FALL_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_HUSKY_FALL_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_HUSKY_FALL_SPRITE_DIRECTION,
  DEFINING_WORLD_PLAZA_HUSKY_IDLE_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_HUSKY_IDLE_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_HUSKY_JUMP_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_HUSKY_JUMP_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_HUSKY_RUN_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_HUSKY_RUN_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_HUSKY_SPRITE_SCALE,
  DEFINING_WORLD_PLAZA_HUSKY_WALK_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_HUSKY_WALK_MOTION_SHEET_LAYOUT,
} from "@/components/world/domains/definingWorldPlazaHuskySpriteConstants";
import {
  DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_ANCHOR_X_NORMALIZED,
  DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_ANCHOR_Y_NORMALIZED,
  DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_DEFAULT_DIRECTION,
  DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_FALL_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_FALL_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_FALL_SPRITE_DIRECTION,
  DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_IDLE_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_IDLE_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_JUMP_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_JUMP_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_RUN_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_RUN_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_SPRITE_SCALE,
  DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_WALK_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_WALK_MOTION_SHEET_LAYOUT,
} from "@/components/world/domains/definingWorldPlazaGoldenRetrieverSpriteConstants";
import {
  DEFINING_WORLD_PLAZA_GRIZZLY_ANCHOR_X_NORMALIZED,
  DEFINING_WORLD_PLAZA_GRIZZLY_ANCHOR_Y_NORMALIZED,
  DEFINING_WORLD_PLAZA_GRIZZLY_DEFAULT_DIRECTION,
  DEFINING_WORLD_PLAZA_GRIZZLY_FALL_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_GRIZZLY_FALL_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_GRIZZLY_FALL_SPRITE_DIRECTION,
  DEFINING_WORLD_PLAZA_GRIZZLY_IDLE_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_GRIZZLY_IDLE_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_GRIZZLY_JUMP_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_GRIZZLY_JUMP_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_GRIZZLY_RUN_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_GRIZZLY_RUN_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_GRIZZLY_SPRITE_SCALE,
  DEFINING_WORLD_PLAZA_GRIZZLY_WALK_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_GRIZZLY_WALK_MOTION_SHEET_LAYOUT,
} from "@/components/world/domains/definingWorldPlazaGrizzlySpriteConstants";
import {
  DEFINING_WORLD_PLAZA_PINGUIN_ANCHOR_X_NORMALIZED,
  DEFINING_WORLD_PLAZA_PINGUIN_ANCHOR_Y_NORMALIZED,
  DEFINING_WORLD_PLAZA_PINGUIN_DEFAULT_DIRECTION,
  DEFINING_WORLD_PLAZA_PINGUIN_FALL_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_PINGUIN_FALL_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_PINGUIN_FALL_SPRITE_DIRECTION,
  DEFINING_WORLD_PLAZA_PINGUIN_IDLE_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_PINGUIN_IDLE_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_PINGUIN_JUMP_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_PINGUIN_JUMP_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_PINGUIN_RUN_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_PINGUIN_RUN_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_PINGUIN_SPRITE_SCALE,
  DEFINING_WORLD_PLAZA_PINGUIN_WALK_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_PINGUIN_WALK_MOTION_SHEET_LAYOUT,
} from "@/components/world/domains/definingWorldPlazaPinguinSpriteConstants";
import {
  DEFINING_WORLD_PLAZA_CAT_ORANGE_ANCHOR_X_NORMALIZED,
  DEFINING_WORLD_PLAZA_CAT_ORANGE_ANCHOR_Y_NORMALIZED,
  DEFINING_WORLD_PLAZA_CAT_ORANGE_CHARACTER_TEXTURES_QUERY_KEY,
  DEFINING_WORLD_PLAZA_CAT_ORANGE_DEFAULT_DIRECTION,
  DEFINING_WORLD_PLAZA_CAT_ORANGE_FALL_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_CAT_ORANGE_FALL_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_CAT_ORANGE_FALL_SPRITE_DIRECTION,
  DEFINING_WORLD_PLAZA_CAT_ORANGE_IDLE_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_CAT_ORANGE_IDLE_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_CAT_ORANGE_JUMP_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_CAT_ORANGE_JUMP_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_CAT_ORANGE_RUN_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_CAT_ORANGE_RUN_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_CAT_ORANGE_SPRITE_SCALE,
  DEFINING_WORLD_PLAZA_CAT_ORANGE_WALK_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_CAT_ORANGE_WALK_MOTION_SHEET_LAYOUT,
} from "@/components/world/domains/definingWorldPlazaCatOrangeSpriteConstants";
import {
  DEFINING_WORLD_PLAZA_FOX_PEACH_ANCHOR_X_NORMALIZED,
  DEFINING_WORLD_PLAZA_FOX_PEACH_ANCHOR_Y_NORMALIZED,
  DEFINING_WORLD_PLAZA_FOX_PEACH_CHARACTER_TEXTURES_QUERY_KEY,
  DEFINING_WORLD_PLAZA_FOX_PEACH_DEFAULT_DIRECTION,
  DEFINING_WORLD_PLAZA_FOX_PEACH_FALL_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_FOX_PEACH_FALL_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_FOX_PEACH_FALL_SPRITE_DIRECTION,
  DEFINING_WORLD_PLAZA_FOX_PEACH_IDLE_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_FOX_PEACH_IDLE_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_FOX_PEACH_JUMP_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_FOX_PEACH_JUMP_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_FOX_PEACH_RUN_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_FOX_PEACH_RUN_MOTION_SHEET_LAYOUT,
  DEFINING_WORLD_PLAZA_FOX_PEACH_SPRITE_SCALE,
  DEFINING_WORLD_PLAZA_FOX_PEACH_WALK_ANIMATION_FPS,
  DEFINING_WORLD_PLAZA_FOX_PEACH_WALK_MOTION_SHEET_LAYOUT,
  computingWorldPlazaFoxPeachFootOffsetBelowGridAnchorPx,
} from "@/components/world/domains/definingWorldPlazaFoxPeachSpriteConstants";
import type { DefiningWorldPlazaGirlSampleCharacterTextures } from "@/components/world/domains/loadingWorldPlazaGirlSampleCharacterTextures";
import { computingWorldPlazaGirlSampleFootOffsetBelowGridAnchorPx } from "@/components/world/domains/definingWorldPlazaGirlSampleWalkConstants";
import { loadingWorldPlazaCatOrangeCharacterTextures } from "@/components/world/domains/loadingWorldPlazaCatOrangeCharacterTextures";
import { loadingWorldPlazaFoxPeachCharacterTextures } from "@/components/world/domains/loadingWorldPlazaFoxPeachCharacterTextures";
import { loadingWorldPlazaGirlSampleCharacterTextures } from "@/components/world/domains/loadingWorldPlazaGirlSampleCharacterTextures";
import { loadingWorldPlazaGoldenRetrieverCharacterTextures } from "@/components/world/domains/loadingWorldPlazaGoldenRetrieverCharacterTextures";
import { loadingWorldPlazaGrizzlyCharacterTextures } from "@/components/world/domains/loadingWorldPlazaGrizzlyCharacterTextures";
import { loadingWorldPlazaHuskyCharacterTextures } from "@/components/world/domains/loadingWorldPlazaHuskyCharacterTextures";
import { loadingWorldPlazaPinguinCharacterTextures } from "@/components/world/domains/loadingWorldPlazaPinguinCharacterTextures";

/** Gameplay-affecting stats for one selectable avatar skin. */
export interface DefiningWorldPlazaAvatarCharacterGameplayStats {
  /** Multiplies baseline hunger drain (1 = average metabolism). */
  readonly hungerDrainMultiplier: number;
}

/** Presentation bundle for one selectable avatar skin. */
export interface DefiningWorldPlazaAvatarCharacterDefinition {
  readonly skinId: DefiningWorldPlazaAvatarSkinId;
  readonly gameplayStats: DefiningWorldPlazaAvatarCharacterGameplayStats;
  readonly loadTextures: () => Promise<DefiningWorldPlazaGirlSampleCharacterTextures>;
  readonly texturesQueryKey: readonly unknown[];
  readonly walkSheetLayout: DefiningWorldPlazaGirlSampleMotionSheetLayout;
  readonly runSheetLayout: DefiningWorldPlazaGirlSampleMotionSheetLayout;
  readonly jumpSheetLayout: DefiningWorldPlazaGirlSampleMotionSheetLayout;
  readonly idleSheetLayout: DefiningWorldPlazaGirlSampleMotionSheetLayout;
  readonly fallSheetLayout: DefiningWorldPlazaGirlSampleMotionSheetLayout;
  readonly walkAnimationFps: number;
  readonly runAnimationFps: number;
  readonly jumpAnimationFps: number;
  readonly idleAnimationFps: number;
  readonly fallAnimationFps: number;
  readonly fallSpriteDirection: DefiningWorldPlazaGirlSampleWalkDirection;
  readonly anchorXNormalized: number;
  readonly anchorYNormalized: number;
  readonly spriteScale: number;
  /** Distance from grid anchor to painted feet for ground shadow placement. */
  readonly footOffsetBelowGridAnchorPx?: number;
  readonly defaultDirection: DefiningWorldPlazaGirlSampleWalkDirection;
}

/** GirlSample skin: the original 8-direction plaza test avatar. */
const DEFINING_WORLD_PLAZA_GIRL_SAMPLE_CHARACTER_DEFINITION: DefiningWorldPlazaAvatarCharacterDefinition =
  {
    skinId: DEFINING_WORLD_PLAZA_AVATAR_SKIN.GIRL_SAMPLE,
    gameplayStats: { hungerDrainMultiplier: 1.0 },
    loadTextures: loadingWorldPlazaGirlSampleCharacterTextures,
    texturesQueryKey: DEFINING_WORLD_PLAZA_GIRL_SAMPLE_CHARACTER_TEXTURES_QUERY_KEY,
    walkSheetLayout: DEFINING_WORLD_PLAZA_GIRL_SAMPLE_WALK_MOTION_SHEET_LAYOUT,
    runSheetLayout: DEFINING_WORLD_PLAZA_GIRL_SAMPLE_RUN_MOTION_SHEET_LAYOUT,
    jumpSheetLayout: DEFINING_WORLD_PLAZA_GIRL_SAMPLE_JUMP_MOTION_SHEET_LAYOUT,
    idleSheetLayout: DEFINING_WORLD_PLAZA_GIRL_SAMPLE_IDLE_MOTION_SHEET_LAYOUT,
    fallSheetLayout: DEFINING_WORLD_PLAZA_GIRL_SAMPLE_FALL_MOTION_SHEET_LAYOUT,
    walkAnimationFps: DEFINING_WORLD_PLAZA_GIRL_SAMPLE_WALK_ANIMATION_FPS,
    runAnimationFps: DEFINING_WORLD_PLAZA_GIRL_SAMPLE_RUN_ANIMATION_FPS,
    jumpAnimationFps: DEFINING_WORLD_PLAZA_GIRL_SAMPLE_JUMP_ANIMATION_FPS,
    idleAnimationFps: DEFINING_WORLD_PLAZA_GIRL_SAMPLE_IDLE_ANIMATION_FPS,
    fallAnimationFps: DEFINING_WORLD_PLAZA_GIRL_SAMPLE_FALL_ANIMATION_FPS,
    fallSpriteDirection: DEFINING_WORLD_PLAZA_GIRL_SAMPLE_FALL_SPRITE_DIRECTION,
    anchorXNormalized: DEFINING_WORLD_PLAZA_GIRL_SAMPLE_WALK_ANCHOR_X_NORMALIZED,
    anchorYNormalized: DEFINING_WORLD_PLAZA_GIRL_SAMPLE_WALK_ANCHOR_Y_NORMALIZED,
    spriteScale: DEFINING_WORLD_PLAZA_GIRL_SAMPLE_WALK_SPRITE_SCALE,
    defaultDirection: DEFINING_WORLD_PLAZA_GIRL_SAMPLE_WALK_DEFAULT_DIRECTION,
  };

/** Husky skin: top-down 8-direction dog packed one motion per sheet. */
const DEFINING_WORLD_PLAZA_HUSKY_CHARACTER_DEFINITION: DefiningWorldPlazaAvatarCharacterDefinition =
  {
    skinId: DEFINING_WORLD_PLAZA_AVATAR_SKIN.HUSKY,
    gameplayStats: { hungerDrainMultiplier: 1.15 },
    loadTextures: loadingWorldPlazaHuskyCharacterTextures,
    texturesQueryKey: DEFINING_WORLD_PLAZA_HUSKY_CHARACTER_TEXTURES_QUERY_KEY,
    walkSheetLayout: DEFINING_WORLD_PLAZA_HUSKY_WALK_MOTION_SHEET_LAYOUT,
    runSheetLayout: DEFINING_WORLD_PLAZA_HUSKY_RUN_MOTION_SHEET_LAYOUT,
    jumpSheetLayout: DEFINING_WORLD_PLAZA_HUSKY_JUMP_MOTION_SHEET_LAYOUT,
    idleSheetLayout: DEFINING_WORLD_PLAZA_HUSKY_IDLE_MOTION_SHEET_LAYOUT,
    fallSheetLayout: DEFINING_WORLD_PLAZA_HUSKY_FALL_MOTION_SHEET_LAYOUT,
    walkAnimationFps: DEFINING_WORLD_PLAZA_HUSKY_WALK_ANIMATION_FPS,
    runAnimationFps: DEFINING_WORLD_PLAZA_HUSKY_RUN_ANIMATION_FPS,
    jumpAnimationFps: DEFINING_WORLD_PLAZA_HUSKY_JUMP_ANIMATION_FPS,
    idleAnimationFps: DEFINING_WORLD_PLAZA_HUSKY_IDLE_ANIMATION_FPS,
    fallAnimationFps: DEFINING_WORLD_PLAZA_HUSKY_FALL_ANIMATION_FPS,
    fallSpriteDirection: DEFINING_WORLD_PLAZA_HUSKY_FALL_SPRITE_DIRECTION,
    anchorXNormalized: DEFINING_WORLD_PLAZA_HUSKY_ANCHOR_X_NORMALIZED,
    anchorYNormalized: DEFINING_WORLD_PLAZA_HUSKY_ANCHOR_Y_NORMALIZED,
    spriteScale: DEFINING_WORLD_PLAZA_HUSKY_SPRITE_SCALE,
    defaultDirection: DEFINING_WORLD_PLAZA_HUSKY_DEFAULT_DIRECTION,
  };

/** TanStack Query key for loaded Golden Retriever character textures. */
const DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_CHARACTER_TEXTURES_QUERY_KEY = [
  "world-plaza",
  "golden-retriever",
  "character-textures",
  "shadowless",
  "8-direction",
  "15-frame",
] as const;

/** Golden Retriever skin: top-down 8-direction dog packed one motion per sheet. */
const DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_CHARACTER_DEFINITION: DefiningWorldPlazaAvatarCharacterDefinition =
  {
    skinId: DEFINING_WORLD_PLAZA_AVATAR_SKIN.GOLDEN_RETRIEVER,
    gameplayStats: { hungerDrainMultiplier: 1.0 },
    loadTextures: loadingWorldPlazaGoldenRetrieverCharacterTextures,
    texturesQueryKey:
      DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_CHARACTER_TEXTURES_QUERY_KEY,
    walkSheetLayout:
      DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_WALK_MOTION_SHEET_LAYOUT,
    runSheetLayout:
      DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_RUN_MOTION_SHEET_LAYOUT,
    jumpSheetLayout:
      DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_JUMP_MOTION_SHEET_LAYOUT,
    idleSheetLayout:
      DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_IDLE_MOTION_SHEET_LAYOUT,
    fallSheetLayout:
      DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_FALL_MOTION_SHEET_LAYOUT,
    walkAnimationFps: DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_WALK_ANIMATION_FPS,
    runAnimationFps: DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_RUN_ANIMATION_FPS,
    jumpAnimationFps: DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_JUMP_ANIMATION_FPS,
    idleAnimationFps: DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_IDLE_ANIMATION_FPS,
    fallAnimationFps: DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_FALL_ANIMATION_FPS,
    fallSpriteDirection:
      DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_FALL_SPRITE_DIRECTION,
    anchorXNormalized:
      DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_ANCHOR_X_NORMALIZED,
    anchorYNormalized:
      DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_ANCHOR_Y_NORMALIZED,
    spriteScale: DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_SPRITE_SCALE,
    defaultDirection: DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_DEFAULT_DIRECTION,
  };

/** TanStack Query key for loaded Grizzly character textures. */
const DEFINING_WORLD_PLAZA_GRIZZLY_CHARACTER_TEXTURES_QUERY_KEY = [
  "world-plaza",
  "grizzly",
  "character-textures",
  "shadowless",
  "8-direction",
  "15-frame",
  "96px",
] as const;

/** Grizzly skin: top-down 8-direction bear packed one motion per sheet. */
const DEFINING_WORLD_PLAZA_GRIZZLY_CHARACTER_DEFINITION: DefiningWorldPlazaAvatarCharacterDefinition =
  {
    skinId: DEFINING_WORLD_PLAZA_AVATAR_SKIN.GRIZZLY,
    gameplayStats: { hungerDrainMultiplier: 1.3 },
    loadTextures: loadingWorldPlazaGrizzlyCharacterTextures,
    texturesQueryKey: DEFINING_WORLD_PLAZA_GRIZZLY_CHARACTER_TEXTURES_QUERY_KEY,
    walkSheetLayout: DEFINING_WORLD_PLAZA_GRIZZLY_WALK_MOTION_SHEET_LAYOUT,
    runSheetLayout: DEFINING_WORLD_PLAZA_GRIZZLY_RUN_MOTION_SHEET_LAYOUT,
    jumpSheetLayout: DEFINING_WORLD_PLAZA_GRIZZLY_JUMP_MOTION_SHEET_LAYOUT,
    idleSheetLayout: DEFINING_WORLD_PLAZA_GRIZZLY_IDLE_MOTION_SHEET_LAYOUT,
    fallSheetLayout: DEFINING_WORLD_PLAZA_GRIZZLY_FALL_MOTION_SHEET_LAYOUT,
    walkAnimationFps: DEFINING_WORLD_PLAZA_GRIZZLY_WALK_ANIMATION_FPS,
    runAnimationFps: DEFINING_WORLD_PLAZA_GRIZZLY_RUN_ANIMATION_FPS,
    jumpAnimationFps: DEFINING_WORLD_PLAZA_GRIZZLY_JUMP_ANIMATION_FPS,
    idleAnimationFps: DEFINING_WORLD_PLAZA_GRIZZLY_IDLE_ANIMATION_FPS,
    fallAnimationFps: DEFINING_WORLD_PLAZA_GRIZZLY_FALL_ANIMATION_FPS,
    fallSpriteDirection: DEFINING_WORLD_PLAZA_GRIZZLY_FALL_SPRITE_DIRECTION,
    anchorXNormalized: DEFINING_WORLD_PLAZA_GRIZZLY_ANCHOR_X_NORMALIZED,
    anchorYNormalized: DEFINING_WORLD_PLAZA_GRIZZLY_ANCHOR_Y_NORMALIZED,
    spriteScale: DEFINING_WORLD_PLAZA_GRIZZLY_SPRITE_SCALE,
    defaultDirection: DEFINING_WORLD_PLAZA_GRIZZLY_DEFAULT_DIRECTION,
  };

/** TanStack Query key for loaded Pinguin character textures. */
const DEFINING_WORLD_PLAZA_PINGUIN_CHARACTER_TEXTURES_QUERY_KEY = [
  "world-plaza",
  "pinguin",
  "character-textures",
  "shadowless",
  "8-direction",
  "15-frame",
] as const;

/** Pinguin skin: top-down 8-direction penguin packed one motion per sheet. */
const DEFINING_WORLD_PLAZA_PINGUIN_CHARACTER_DEFINITION: DefiningWorldPlazaAvatarCharacterDefinition =
  {
    skinId: DEFINING_WORLD_PLAZA_AVATAR_SKIN.PINGUIN,
    gameplayStats: { hungerDrainMultiplier: 0.85 },
    loadTextures: loadingWorldPlazaPinguinCharacterTextures,
    texturesQueryKey: DEFINING_WORLD_PLAZA_PINGUIN_CHARACTER_TEXTURES_QUERY_KEY,
    walkSheetLayout: DEFINING_WORLD_PLAZA_PINGUIN_WALK_MOTION_SHEET_LAYOUT,
    runSheetLayout: DEFINING_WORLD_PLAZA_PINGUIN_RUN_MOTION_SHEET_LAYOUT,
    jumpSheetLayout: DEFINING_WORLD_PLAZA_PINGUIN_JUMP_MOTION_SHEET_LAYOUT,
    idleSheetLayout: DEFINING_WORLD_PLAZA_PINGUIN_IDLE_MOTION_SHEET_LAYOUT,
    fallSheetLayout: DEFINING_WORLD_PLAZA_PINGUIN_FALL_MOTION_SHEET_LAYOUT,
    walkAnimationFps: DEFINING_WORLD_PLAZA_PINGUIN_WALK_ANIMATION_FPS,
    runAnimationFps: DEFINING_WORLD_PLAZA_PINGUIN_RUN_ANIMATION_FPS,
    jumpAnimationFps: DEFINING_WORLD_PLAZA_PINGUIN_JUMP_ANIMATION_FPS,
    idleAnimationFps: DEFINING_WORLD_PLAZA_PINGUIN_IDLE_ANIMATION_FPS,
    fallAnimationFps: DEFINING_WORLD_PLAZA_PINGUIN_FALL_ANIMATION_FPS,
    fallSpriteDirection: DEFINING_WORLD_PLAZA_PINGUIN_FALL_SPRITE_DIRECTION,
    anchorXNormalized: DEFINING_WORLD_PLAZA_PINGUIN_ANCHOR_X_NORMALIZED,
    anchorYNormalized: DEFINING_WORLD_PLAZA_PINGUIN_ANCHOR_Y_NORMALIZED,
    spriteScale: DEFINING_WORLD_PLAZA_PINGUIN_SPRITE_SCALE,
    defaultDirection: DEFINING_WORLD_PLAZA_PINGUIN_DEFAULT_DIRECTION,
  };

/** Fox Peach skin: per-direction walk and idle strips, 256 px frames. */
const DEFINING_WORLD_PLAZA_FOX_PEACH_CHARACTER_DEFINITION: DefiningWorldPlazaAvatarCharacterDefinition =
  {
    skinId: DEFINING_WORLD_PLAZA_AVATAR_SKIN.FOX_PEACH,
    gameplayStats: { hungerDrainMultiplier: 1.0 },
    loadTextures: loadingWorldPlazaFoxPeachCharacterTextures,
    texturesQueryKey: DEFINING_WORLD_PLAZA_FOX_PEACH_CHARACTER_TEXTURES_QUERY_KEY,
    walkSheetLayout: DEFINING_WORLD_PLAZA_FOX_PEACH_WALK_MOTION_SHEET_LAYOUT,
    runSheetLayout: DEFINING_WORLD_PLAZA_FOX_PEACH_RUN_MOTION_SHEET_LAYOUT,
    jumpSheetLayout: DEFINING_WORLD_PLAZA_FOX_PEACH_JUMP_MOTION_SHEET_LAYOUT,
    idleSheetLayout: DEFINING_WORLD_PLAZA_FOX_PEACH_IDLE_MOTION_SHEET_LAYOUT,
    fallSheetLayout: DEFINING_WORLD_PLAZA_FOX_PEACH_FALL_MOTION_SHEET_LAYOUT,
    walkAnimationFps: DEFINING_WORLD_PLAZA_FOX_PEACH_WALK_ANIMATION_FPS,
    runAnimationFps: DEFINING_WORLD_PLAZA_FOX_PEACH_RUN_ANIMATION_FPS,
    jumpAnimationFps: DEFINING_WORLD_PLAZA_FOX_PEACH_JUMP_ANIMATION_FPS,
    idleAnimationFps: DEFINING_WORLD_PLAZA_FOX_PEACH_IDLE_ANIMATION_FPS,
    fallAnimationFps: DEFINING_WORLD_PLAZA_FOX_PEACH_FALL_ANIMATION_FPS,
    fallSpriteDirection: DEFINING_WORLD_PLAZA_FOX_PEACH_FALL_SPRITE_DIRECTION,
    anchorXNormalized: DEFINING_WORLD_PLAZA_FOX_PEACH_ANCHOR_X_NORMALIZED,
    anchorYNormalized: DEFINING_WORLD_PLAZA_FOX_PEACH_ANCHOR_Y_NORMALIZED,
    spriteScale: DEFINING_WORLD_PLAZA_FOX_PEACH_SPRITE_SCALE,
    footOffsetBelowGridAnchorPx:
      computingWorldPlazaFoxPeachFootOffsetBelowGridAnchorPx(),
    defaultDirection: DEFINING_WORLD_PLAZA_FOX_PEACH_DEFAULT_DIRECTION,
  };

/** Cat Orange skin: top-down 8-direction cat packed one motion per sheet. */
const DEFINING_WORLD_PLAZA_CAT_ORANGE_CHARACTER_DEFINITION: DefiningWorldPlazaAvatarCharacterDefinition =
  {
    skinId: DEFINING_WORLD_PLAZA_AVATAR_SKIN.CAT_ORANGE,
    gameplayStats: { hungerDrainMultiplier: 0.9 },
    loadTextures: loadingWorldPlazaCatOrangeCharacterTextures,
    texturesQueryKey:
      DEFINING_WORLD_PLAZA_CAT_ORANGE_CHARACTER_TEXTURES_QUERY_KEY,
    walkSheetLayout: DEFINING_WORLD_PLAZA_CAT_ORANGE_WALK_MOTION_SHEET_LAYOUT,
    runSheetLayout: DEFINING_WORLD_PLAZA_CAT_ORANGE_RUN_MOTION_SHEET_LAYOUT,
    jumpSheetLayout: DEFINING_WORLD_PLAZA_CAT_ORANGE_JUMP_MOTION_SHEET_LAYOUT,
    idleSheetLayout: DEFINING_WORLD_PLAZA_CAT_ORANGE_IDLE_MOTION_SHEET_LAYOUT,
    fallSheetLayout: DEFINING_WORLD_PLAZA_CAT_ORANGE_FALL_MOTION_SHEET_LAYOUT,
    walkAnimationFps: DEFINING_WORLD_PLAZA_CAT_ORANGE_WALK_ANIMATION_FPS,
    runAnimationFps: DEFINING_WORLD_PLAZA_CAT_ORANGE_RUN_ANIMATION_FPS,
    jumpAnimationFps: DEFINING_WORLD_PLAZA_CAT_ORANGE_JUMP_ANIMATION_FPS,
    idleAnimationFps: DEFINING_WORLD_PLAZA_CAT_ORANGE_IDLE_ANIMATION_FPS,
    fallAnimationFps: DEFINING_WORLD_PLAZA_CAT_ORANGE_FALL_ANIMATION_FPS,
    fallSpriteDirection: DEFINING_WORLD_PLAZA_CAT_ORANGE_FALL_SPRITE_DIRECTION,
    anchorXNormalized: DEFINING_WORLD_PLAZA_CAT_ORANGE_ANCHOR_X_NORMALIZED,
    anchorYNormalized: DEFINING_WORLD_PLAZA_CAT_ORANGE_ANCHOR_Y_NORMALIZED,
    spriteScale: DEFINING_WORLD_PLAZA_CAT_ORANGE_SPRITE_SCALE,
    defaultDirection: DEFINING_WORLD_PLAZA_CAT_ORANGE_DEFAULT_DIRECTION,
  };

/** Character definition for each selectable skin id. */
export const DEFINING_WORLD_PLAZA_AVATAR_CHARACTER_DEFINITIONS: Record<
  DefiningWorldPlazaAvatarSkinId,
  DefiningWorldPlazaAvatarCharacterDefinition
> = {
  [DEFINING_WORLD_PLAZA_AVATAR_SKIN.GIRL_SAMPLE]:
    DEFINING_WORLD_PLAZA_GIRL_SAMPLE_CHARACTER_DEFINITION,
  [DEFINING_WORLD_PLAZA_AVATAR_SKIN.HUSKY]:
    DEFINING_WORLD_PLAZA_HUSKY_CHARACTER_DEFINITION,
  [DEFINING_WORLD_PLAZA_AVATAR_SKIN.GOLDEN_RETRIEVER]:
    DEFINING_WORLD_PLAZA_GOLDEN_RETRIEVER_CHARACTER_DEFINITION,
  [DEFINING_WORLD_PLAZA_AVATAR_SKIN.GRIZZLY]:
    DEFINING_WORLD_PLAZA_GRIZZLY_CHARACTER_DEFINITION,
  [DEFINING_WORLD_PLAZA_AVATAR_SKIN.PINGUIN]:
    DEFINING_WORLD_PLAZA_PINGUIN_CHARACTER_DEFINITION,
  [DEFINING_WORLD_PLAZA_AVATAR_SKIN.FOX_PEACH]:
    DEFINING_WORLD_PLAZA_FOX_PEACH_CHARACTER_DEFINITION,
  [DEFINING_WORLD_PLAZA_AVATAR_SKIN.CAT_ORANGE]:
    DEFINING_WORLD_PLAZA_CAT_ORANGE_CHARACTER_DEFINITION,
};

/**
 * Resolves the character definition for a selected skin id.
 *
 * @param skinId - Currently selected avatar skin id.
 */
export function resolvingWorldPlazaAvatarCharacterDefinition(
  skinId: DefiningWorldPlazaAvatarSkinId,
): DefiningWorldPlazaAvatarCharacterDefinition {
  return (
    DEFINING_WORLD_PLAZA_AVATAR_CHARACTER_DEFINITIONS[skinId] ??
    DEFINING_WORLD_PLAZA_AVATAR_CHARACTER_DEFINITIONS[
      DEFINING_WORLD_PLAZA_AVATAR_SKIN_DEFAULT
    ]
  );
}

/**
 * Resolves painted-foot offset below the grid anchor for one avatar skin.
 *
 * @param characterDefinition - Active avatar presentation bundle.
 */
export function resolvingWorldPlazaAvatarFootOffsetBelowGridAnchorPx(
  characterDefinition: DefiningWorldPlazaAvatarCharacterDefinition,
): number {
  return (
    characterDefinition.footOffsetBelowGridAnchorPx ??
    computingWorldPlazaGirlSampleFootOffsetBelowGridAnchorPx()
  );
}
