/**
 * Species-specific raw and cooked meat catalog for wildlife loot and cooking.
 *
 * @module components/world/wildlife/domains/definingWildlifeMeatRegistry
 */

import type { DefiningWorldPlazaEntityDiseaseId } from '@/components/world/health/domains/definingWorldPlazaEntityDiseaseRegistry';
import type { DefiningWildlifeSpeciesId } from '@/components/world/wildlife/domains/definingWildlifeTypes';
import { DEFINING_WILDLIFE_VARIANT_MEAT_CATALOG } from '@/components/world/wildlife/domains/definingWildlifeVariantMeatRegistry';

/** Shared raw-meat poison tuning (flat EV over duration) for non-species fallback. */
export const DEFINING_WILDLIFE_RAW_MEAT_POISON_FLAT_EV = 5;

/** Raw meat poison duration (ms) for non-species fallback. */
export const DEFINING_WILDLIFE_RAW_MEAT_POISON_DURATION_MS = 60_000;

/** Legacy sickness chance kept for generic fallback food. */
export const DEFINING_WILDLIFE_RAW_MEAT_SICKNESS_CHANCE = 0.35;

/** Hunger restore multiplier while food-sickness debuff or disease is active. */
export const DEFINING_WILDLIFE_FOOD_SICKNESS_HUNGER_MULTIPLIER = 0.5;

export type DefiningWildlifeMeatCatalogEntry = {
  speciesId: DefiningWildlifeSpeciesId;
  rawItemTypeId: string;
  cookedItemTypeId: string;
  rawDisplayName: string;
  cookedDisplayName: string;
  rawHungerRestoreRatio: number;
  cookedHungerRestoreRatio: number;
  lootQuantity: number;
  /** Campfire cook channel duration for this raw cut (ms). */
  cookDurationMs: number;
  rawDiseaseId: DefiningWorldPlazaEntityDiseaseId;
  rawDiseaseChance: number;
  /** Multiplies symptomStrengthMultiplier at contract (1 = baseline). */
  rawSymptomIntensity?: number;
  /** Multiplies durationMultiplier at contract (1 = baseline). */
  rawDurationIntensity?: number;
  cookedWellFedBuffId: string;
  cookedWellFedChance: number;
  /** Optional extra well-fed buffs applied together when cooked meat is eaten. */
  cookedWellFedBuffIds?: readonly string[];
  /** Prion-style diseases that survive cooking at reduced odds. */
  cookedResidualDiseaseId?: DefiningWorldPlazaEntityDiseaseId;
  cookedResidualDiseaseChance?: number;
};

export const DEFINING_WILDLIFE_MEAT_CATALOG: readonly DefiningWildlifeMeatCatalogEntry[] =
  [
    {
      speciesId: 'chicken',
      rawItemTypeId: 'world-plaza-raw-chicken-meat',
      cookedItemTypeId: 'world-plaza-cooked-chicken-meat',
      rawDisplayName: 'Raw Chicken Meat',
      cookedDisplayName: 'Cooked Chicken Meat',
      rawHungerRestoreRatio: 0.12,
      cookedHungerRestoreRatio: 0.3,
      lootQuantity: 1,
      cookDurationMs: 2_500,
      rawDiseaseId: 'salmonellosis',
      rawDiseaseChance: 0.45,
      cookedWellFedBuffId: 'well-fed-comfort-buff',
      cookedWellFedChance: 0.35,
    },
    {
      speciesId: 'shepherd-dog',
      rawItemTypeId: 'world-plaza-raw-shepherd-dog-meat',
      cookedItemTypeId: 'world-plaza-cooked-shepherd-dog-meat',
      rawDisplayName: 'Raw Dog Meat',
      cookedDisplayName: 'Cooked Dog Meat',
      rawHungerRestoreRatio: 0.14,
      cookedHungerRestoreRatio: 0.32,
      lootQuantity: 1,
      cookDurationMs: 2_800,
      rawDiseaseId: 'feline-gut',
      rawDiseaseChance: 0.35,
      cookedWellFedBuffId: 'well-fed-comfort-buff',
      cookedWellFedChance: 0.3,
    },
    {
      speciesId: 'husky',
      rawItemTypeId: 'world-plaza-raw-husky-meat',
      cookedItemTypeId: 'world-plaza-cooked-husky-meat',
      rawDisplayName: 'Raw Dog Meat',
      cookedDisplayName: 'Cooked Dog Meat',
      rawHungerRestoreRatio: 0.14,
      cookedHungerRestoreRatio: 0.32,
      lootQuantity: 1,
      cookDurationMs: 2_800,
      rawDiseaseId: 'feline-gut',
      rawDiseaseChance: 0.35,
      cookedWellFedBuffId: 'well-fed-comfort-buff',
      cookedWellFedChance: 0.3,
    },
    {
      speciesId: 'golden-retriever',
      rawItemTypeId: 'world-plaza-raw-golden-retriever-meat',
      cookedItemTypeId: 'world-plaza-cooked-golden-retriever-meat',
      rawDisplayName: 'Raw Dog Meat',
      cookedDisplayName: 'Cooked Dog Meat',
      rawHungerRestoreRatio: 0.14,
      cookedHungerRestoreRatio: 0.32,
      lootQuantity: 1,
      cookDurationMs: 2_800,
      rawDiseaseId: 'feline-gut',
      rawDiseaseChance: 0.35,
      cookedWellFedBuffId: 'well-fed-comfort-buff',
      cookedWellFedChance: 0.3,
    },
    {
      speciesId: 'cat-black',
      rawItemTypeId: 'world-plaza-raw-cat-black-meat',
      cookedItemTypeId: 'world-plaza-cooked-cat-black-meat',
      rawDisplayName: 'Raw Cat Meat',
      cookedDisplayName: 'Cooked Cat Meat',
      rawHungerRestoreRatio: 0.1,
      cookedHungerRestoreRatio: 0.26,
      lootQuantity: 1,
      cookDurationMs: 2_200,
      rawDiseaseId: 'feline-gut',
      rawDiseaseChance: 0.4,
      cookedWellFedBuffId: 'well-fed-comfort-buff',
      cookedWellFedChance: 0.28,
    },
    {
      speciesId: 'cat-white',
      rawItemTypeId: 'world-plaza-raw-cat-white-meat',
      cookedItemTypeId: 'world-plaza-cooked-cat-white-meat',
      rawDisplayName: 'Raw Cat Meat',
      cookedDisplayName: 'Cooked Cat Meat',
      rawHungerRestoreRatio: 0.1,
      cookedHungerRestoreRatio: 0.26,
      lootQuantity: 1,
      cookDurationMs: 2_200,
      rawDiseaseId: 'feline-gut',
      rawDiseaseChance: 0.4,
      cookedWellFedBuffId: 'well-fed-comfort-buff',
      cookedWellFedChance: 0.28,
    },
    {
      speciesId: 'cat-large',
      rawItemTypeId: 'world-plaza-raw-cat-large-meat',
      cookedItemTypeId: 'world-plaza-cooked-cat-large-meat',
      rawDisplayName: 'Raw Cat Meat',
      cookedDisplayName: 'Cooked Cat Meat',
      rawHungerRestoreRatio: 0.12,
      cookedHungerRestoreRatio: 0.3,
      lootQuantity: 1,
      cookDurationMs: 2_400,
      rawDiseaseId: 'feline-gut',
      rawDiseaseChance: 0.38,
      cookedWellFedBuffId: 'well-fed-comfort-buff',
      cookedWellFedChance: 0.3,
    },
    {
      speciesId: 'cat-orange',
      rawItemTypeId: 'world-plaza-raw-cat-orange-meat',
      cookedItemTypeId: 'world-plaza-cooked-cat-orange-meat',
      rawDisplayName: 'Raw Cat Meat',
      cookedDisplayName: 'Cooked Cat Meat',
      rawHungerRestoreRatio: 0.1,
      cookedHungerRestoreRatio: 0.26,
      lootQuantity: 1,
      cookDurationMs: 2_200,
      rawDiseaseId: 'feline-gut',
      rawDiseaseChance: 0.4,
      cookedWellFedBuffId: 'well-fed-comfort-buff',
      cookedWellFedChance: 0.28,
    },
    {
      speciesId: 'deer',
      rawItemTypeId: 'world-plaza-raw-deer-meat',
      cookedItemTypeId: 'world-plaza-cooked-deer-meat',
      rawDisplayName: 'Raw Deer Meat',
      cookedDisplayName: 'Cooked Deer Meat',
      rawHungerRestoreRatio: 0.22,
      cookedHungerRestoreRatio: 0.48,
      lootQuantity: 1,
      cookDurationMs: 4_000,
      rawDiseaseId: 'chronic-wasting',
      rawDiseaseChance: 0.35,
      cookedWellFedBuffId: 'well-fed-fleet-buff',
      cookedWellFedChance: 0.4,
      cookedResidualDiseaseId: 'chronic-wasting',
      cookedResidualDiseaseChance: 0.05,
    },
    {
      speciesId: 'boar',
      rawItemTypeId: 'world-plaza-raw-boar-meat',
      cookedItemTypeId: 'world-plaza-cooked-boar-meat',
      rawDisplayName: 'Raw Boar Meat',
      cookedDisplayName: 'Cooked Boar Meat',
      rawHungerRestoreRatio: 0.28,
      cookedHungerRestoreRatio: 0.55,
      lootQuantity: 1,
      cookDurationMs: 6_500,
      rawDiseaseId: 'trichinellosis',
      rawDiseaseChance: 0.4,
      cookedWellFedBuffId: 'well-fed-toughened-buff',
      cookedWellFedChance: 0.38,
    },
    {
      speciesId: 'cow',
      rawItemTypeId: 'world-plaza-raw-beef',
      cookedItemTypeId: 'world-plaza-cooked-beef',
      rawDisplayName: 'Raw Beef',
      cookedDisplayName: 'Cooked Beef',
      rawHungerRestoreRatio: 0.32,
      cookedHungerRestoreRatio: 0.62,
      lootQuantity: 1,
      cookDurationMs: 8_000,
      rawDiseaseId: 'mad-cow',
      rawDiseaseChance: 0.3,
      cookedWellFedBuffId: 'well-fed-prime-buff',
      cookedWellFedChance: 0.42,
      cookedResidualDiseaseId: 'mad-cow',
      cookedResidualDiseaseChance: 0.03,
    },
    {
      speciesId: 'cow-brown',
      rawItemTypeId: 'world-plaza-raw-brown-beef',
      cookedItemTypeId: 'world-plaza-cooked-brown-beef',
      rawDisplayName: 'Raw Beef',
      cookedDisplayName: 'Cooked Beef',
      rawHungerRestoreRatio: 0.32,
      cookedHungerRestoreRatio: 0.62,
      lootQuantity: 1,
      cookDurationMs: 8_000,
      rawDiseaseId: 'mad-cow',
      rawDiseaseChance: 0.3,
      cookedWellFedBuffId: 'well-fed-prime-buff',
      cookedWellFedChance: 0.42,
      cookedResidualDiseaseId: 'mad-cow',
      cookedResidualDiseaseChance: 0.03,
    },
    {
      speciesId: 'sheep',
      rawItemTypeId: 'world-plaza-raw-mutton',
      cookedItemTypeId: 'world-plaza-cooked-mutton',
      rawDisplayName: 'Raw Mutton',
      cookedDisplayName: 'Cooked Mutton',
      rawHungerRestoreRatio: 0.24,
      cookedHungerRestoreRatio: 0.46,
      lootQuantity: 1,
      cookDurationMs: 5_000,
      rawDiseaseId: 'liver-fluke',
      rawDiseaseChance: 0.35,
      cookedWellFedBuffId: 'well-fed-vigor-buff',
      cookedWellFedChance: 0.36,
    },
    {
      speciesId: 'zebra',
      rawItemTypeId: 'world-plaza-raw-zebra-meat',
      cookedItemTypeId: 'world-plaza-cooked-zebra-meat',
      rawDisplayName: 'Raw Zebra Meat',
      cookedDisplayName: 'Cooked Zebra Meat',
      rawHungerRestoreRatio: 0.26,
      cookedHungerRestoreRatio: 0.5,
      lootQuantity: 1,
      cookDurationMs: 5_500,
      rawDiseaseId: 'sleeping-sickness',
      rawDiseaseChance: 0.38,
      cookedWellFedBuffId: 'well-fed-endurance-buff',
      cookedWellFedChance: 0.4,
    },
    {
      speciesId: 'grey-wolf',
      rawItemTypeId: 'world-plaza-raw-wolf-meat',
      cookedItemTypeId: 'world-plaza-cooked-wolf-meat',
      rawDisplayName: 'Raw Wolf Meat',
      cookedDisplayName: 'Cooked Wolf Meat',
      rawHungerRestoreRatio: 0.2,
      cookedHungerRestoreRatio: 0.42,
      lootQuantity: 1,
      cookDurationMs: 4_500,
      rawDiseaseId: 'wolf-fever',
      rawDiseaseChance: 0.42,
      cookedWellFedBuffId: 'well-fed-strength-buff',
      cookedWellFedChance: 0.35,
    },
    {
      speciesId: 'omega-wolf',
      rawItemTypeId: 'world-plaza-raw-omega-wolf-meat',
      cookedItemTypeId: 'world-plaza-cooked-omega-wolf-meat',
      rawDisplayName: 'Raw Omega Wolf Meat',
      cookedDisplayName: 'Cooked Omega Wolf Meat',
      rawHungerRestoreRatio: 0.28,
      cookedHungerRestoreRatio: 0.55,
      lootQuantity: 2,
      cookDurationMs: 6_000,
      rawDiseaseId: 'wolf-fever',
      rawDiseaseChance: 0.5,
      cookedWellFedBuffId: 'well-fed-strength-buff',
      cookedWellFedBuffIds: [
        'well-fed-strength-buff',
        'well-fed-omega-skew-buff',
        'well-fed-omega-siphon-buff',
      ],
      cookedWellFedChance: 0.5,
    },
    {
      speciesId: 'brown-bear',
      rawItemTypeId: 'world-plaza-raw-bear-meat',
      cookedItemTypeId: 'world-plaza-cooked-bear-meat',
      rawDisplayName: 'Raw Bear Meat',
      cookedDisplayName: 'Cooked Bear Meat',
      rawHungerRestoreRatio: 0.38,
      cookedHungerRestoreRatio: 0.68,
      lootQuantity: 1,
      cookDurationMs: 10_000,
      rawDiseaseId: 'bear-worm',
      rawDiseaseChance: 0.45,
      cookedWellFedBuffId: 'well-fed-hearty-buff',
      cookedWellFedChance: 0.45,
    },
    {
      speciesId: 'grizzly',
      rawItemTypeId: 'world-plaza-raw-grizzly-meat',
      cookedItemTypeId: 'world-plaza-cooked-grizzly-meat',
      rawDisplayName: 'Raw Bear Meat',
      cookedDisplayName: 'Cooked Bear Meat',
      rawHungerRestoreRatio: 0.4,
      cookedHungerRestoreRatio: 0.7,
      lootQuantity: 1,
      cookDurationMs: 10_500,
      rawDiseaseId: 'bear-worm',
      rawDiseaseChance: 0.48,
      cookedWellFedBuffId: 'well-fed-hearty-buff',
      cookedWellFedChance: 0.46,
    },
    {
      speciesId: 'lion',
      rawItemTypeId: 'world-plaza-raw-lion-meat',
      cookedItemTypeId: 'world-plaza-cooked-lion-meat',
      rawDisplayName: 'Raw Lion Meat',
      cookedDisplayName: 'Cooked Lion Meat',
      rawHungerRestoreRatio: 0.3,
      cookedHungerRestoreRatio: 0.58,
      lootQuantity: 1,
      cookDurationMs: 7_500,
      rawDiseaseId: 'toxoplasmosis',
      rawDiseaseChance: 0.38,
      cookedWellFedBuffId: 'well-fed-strength-buff',
      cookedWellFedChance: 0.4,
    },
    {
      speciesId: 'lioness',
      rawItemTypeId: 'world-plaza-raw-lioness-meat',
      cookedItemTypeId: 'world-plaza-cooked-lioness-meat',
      rawDisplayName: 'Raw Lioness Meat',
      cookedDisplayName: 'Cooked Lioness Meat',
      rawHungerRestoreRatio: 0.28,
      cookedHungerRestoreRatio: 0.56,
      lootQuantity: 1,
      cookDurationMs: 7_000,
      rawDiseaseId: 'toxoplasmosis',
      rawDiseaseChance: 0.36,
      cookedWellFedBuffId: 'well-fed-strength-buff',
      cookedWellFedChance: 0.38,
    },
    {
      speciesId: 'crocodile',
      rawItemTypeId: 'world-plaza-raw-crocodile-meat',
      cookedItemTypeId: 'world-plaza-cooked-crocodile-meat',
      rawDisplayName: 'Raw Crocodile Meat',
      cookedDisplayName: 'Cooked Crocodile Meat',
      rawHungerRestoreRatio: 0.25,
      cookedHungerRestoreRatio: 0.52,
      lootQuantity: 1,
      cookDurationMs: 6_000,
      rawDiseaseId: 'vibrio-infection',
      rawDiseaseChance: 0.4,
      cookedWellFedBuffId: 'well-fed-reptile-buff',
      cookedWellFedChance: 0.37,
    },
    {
      speciesId: 'antilope',
      rawItemTypeId: 'world-plaza-raw-antilope-meat',
      cookedItemTypeId: 'world-plaza-cooked-antilope-meat',
      rawDisplayName: 'Raw Antilope Meat',
      cookedDisplayName: 'Cooked Antilope Meat',
      rawHungerRestoreRatio: 0.2,
      cookedHungerRestoreRatio: 0.44,
      lootQuantity: 1,
      cookDurationMs: 3_500,
      rawDiseaseId: 'sleeping-sickness',
      rawDiseaseChance: 0.36,
      cookedWellFedBuffId: 'well-fed-fleet-buff',
      cookedWellFedChance: 0.4,
    },
    {
      speciesId: 'oryx',
      rawItemTypeId: 'world-plaza-raw-oryx-meat',
      cookedItemTypeId: 'world-plaza-cooked-oryx-meat',
      rawDisplayName: 'Raw Oryx Meat',
      cookedDisplayName: 'Cooked Oryx Meat',
      rawHungerRestoreRatio: 0.24,
      cookedHungerRestoreRatio: 0.48,
      lootQuantity: 1,
      cookDurationMs: 5_000,
      rawDiseaseId: 'liver-fluke',
      rawDiseaseChance: 0.34,
      cookedWellFedBuffId: 'well-fed-endurance-buff',
      cookedWellFedChance: 0.38,
    },
    {
      speciesId: 'giraffe',
      rawItemTypeId: 'world-plaza-raw-giraffe-meat',
      cookedItemTypeId: 'world-plaza-cooked-giraffe-meat',
      rawDisplayName: 'Raw Giraffe Meat',
      cookedDisplayName: 'Cooked Giraffe Meat',
      rawHungerRestoreRatio: 0.34,
      cookedHungerRestoreRatio: 0.6,
      lootQuantity: 2,
      cookDurationMs: 8_500,
      rawDiseaseId: 'sleeping-sickness',
      rawDiseaseChance: 0.34,
      cookedWellFedBuffId: 'well-fed-vigor-buff',
      cookedWellFedChance: 0.4,
    },
    {
      speciesId: 'ostrich',
      rawItemTypeId: 'world-plaza-raw-ostrich-meat',
      cookedItemTypeId: 'world-plaza-cooked-ostrich-meat',
      rawDisplayName: 'Raw Ostrich Meat',
      cookedDisplayName: 'Cooked Ostrich Meat',
      rawHungerRestoreRatio: 0.22,
      cookedHungerRestoreRatio: 0.46,
      lootQuantity: 1,
      cookDurationMs: 4_000,
      rawDiseaseId: 'salmonellosis',
      rawDiseaseChance: 0.42,
      cookedWellFedBuffId: 'well-fed-fleet-buff',
      cookedWellFedChance: 0.38,
    },
    {
      speciesId: 'elephant',
      rawItemTypeId: 'world-plaza-raw-elephant-meat',
      cookedItemTypeId: 'world-plaza-cooked-elephant-meat',
      rawDisplayName: 'Raw Bull Elephant Meat',
      cookedDisplayName: 'Cooked Bull Elephant Meat',
      rawHungerRestoreRatio: 0.42,
      cookedHungerRestoreRatio: 0.72,
      lootQuantity: 3,
      cookDurationMs: 11_500,
      rawDiseaseId: 'tusk-fluke',
      rawDiseaseChance: 0.35,
      cookedWellFedBuffId: 'well-fed-hearty-buff',
      cookedWellFedChance: 0.45,
    },
    {
      speciesId: 'elephant-female',
      rawItemTypeId: 'world-plaza-raw-elephant-matriarch-meat',
      cookedItemTypeId: 'world-plaza-cooked-elephant-matriarch-meat',
      rawDisplayName: 'Raw Elephant Meat',
      cookedDisplayName: 'Cooked Elephant Meat',
      rawHungerRestoreRatio: 0.4,
      cookedHungerRestoreRatio: 0.7,
      lootQuantity: 3,
      cookDurationMs: 11_000,
      rawDiseaseId: 'tusk-fluke',
      rawDiseaseChance: 0.35,
      cookedWellFedBuffId: 'well-fed-hearty-buff',
      cookedWellFedChance: 0.43,
    },
    {
      speciesId: 'rhino',
      rawItemTypeId: 'world-plaza-raw-rhino-meat',
      cookedItemTypeId: 'world-plaza-cooked-rhino-meat',
      rawDisplayName: 'Raw Bull Rhino Meat',
      cookedDisplayName: 'Cooked Bull Rhino Meat',
      rawHungerRestoreRatio: 0.38,
      cookedHungerRestoreRatio: 0.66,
      lootQuantity: 2,
      cookDurationMs: 10_000,
      rawDiseaseId: 'tusk-fluke',
      rawDiseaseChance: 0.36,
      cookedWellFedBuffId: 'well-fed-toughened-buff',
      cookedWellFedChance: 0.42,
    },
    {
      speciesId: 'rhino-female',
      rawItemTypeId: 'world-plaza-raw-rhino-cow-meat',
      cookedItemTypeId: 'world-plaza-cooked-rhino-cow-meat',
      rawDisplayName: 'Raw Rhino Meat',
      cookedDisplayName: 'Cooked Rhino Meat',
      rawHungerRestoreRatio: 0.36,
      cookedHungerRestoreRatio: 0.64,
      lootQuantity: 2,
      cookDurationMs: 9_500,
      rawDiseaseId: 'tusk-fluke',
      rawDiseaseChance: 0.36,
      cookedWellFedBuffId: 'well-fed-toughened-buff',
      cookedWellFedChance: 0.4,
    },
    {
      speciesId: 'hyena',
      rawItemTypeId: 'world-plaza-raw-hyena-meat',
      cookedItemTypeId: 'world-plaza-cooked-hyena-meat',
      rawDisplayName: 'Raw Hyena Meat',
      cookedDisplayName: 'Cooked Hyena Meat',
      rawHungerRestoreRatio: 0.18,
      cookedHungerRestoreRatio: 0.4,
      lootQuantity: 1,
      cookDurationMs: 4_500,
      rawDiseaseId: 'scavenger-rot',
      rawDiseaseChance: 0.44,
      cookedWellFedBuffId: 'well-fed-strength-buff',
      cookedWellFedChance: 0.34,
    },
    {
      speciesId: 'bison',
      rawItemTypeId: 'world-plaza-raw-bison-meat',
      cookedItemTypeId: 'world-plaza-cooked-bison-meat',
      rawDisplayName: 'Raw Bison Meat',
      cookedDisplayName: 'Cooked Bison Meat',
      rawHungerRestoreRatio: 0.36,
      cookedHungerRestoreRatio: 0.66,
      lootQuantity: 2,
      cookDurationMs: 9_000,
      rawDiseaseId: 'mad-cow',
      rawDiseaseChance: 0.3,
      cookedWellFedBuffId: 'well-fed-hearty-buff',
      cookedWellFedChance: 0.42,
      cookedResidualDiseaseId: 'mad-cow',
      cookedResidualDiseaseChance: 0.03,
    },
    {
      speciesId: 'pig',
      rawItemTypeId: 'world-plaza-raw-pork',
      cookedItemTypeId: 'world-plaza-cooked-pork',
      rawDisplayName: 'Raw Pork',
      cookedDisplayName: 'Cooked Pork',
      rawHungerRestoreRatio: 0.26,
      cookedHungerRestoreRatio: 0.52,
      lootQuantity: 1,
      cookDurationMs: 6_000,
      rawDiseaseId: 'trichinellosis',
      rawDiseaseChance: 0.4,
      cookedWellFedBuffId: 'well-fed-comfort-buff',
      cookedWellFedChance: 0.38,
    },
    {
      speciesId: 'bull',
      rawItemTypeId: 'world-plaza-raw-bull-beef',
      cookedItemTypeId: 'world-plaza-cooked-bull-beef',
      rawDisplayName: 'Raw Bull Beef',
      cookedDisplayName: 'Cooked Bull Beef',
      rawHungerRestoreRatio: 0.34,
      cookedHungerRestoreRatio: 0.64,
      lootQuantity: 2,
      cookDurationMs: 8_500,
      rawDiseaseId: 'mad-cow',
      rawDiseaseChance: 0.3,
      cookedWellFedBuffId: 'well-fed-prime-buff',
      cookedWellFedChance: 0.42,
      cookedResidualDiseaseId: 'mad-cow',
      cookedResidualDiseaseChance: 0.03,
    },
    {
      speciesId: 'stag',
      rawItemTypeId: 'world-plaza-raw-stag-venison',
      cookedItemTypeId: 'world-plaza-cooked-stag-venison',
      rawDisplayName: 'Raw Stag Venison',
      cookedDisplayName: 'Cooked Stag Venison',
      rawHungerRestoreRatio: 0.26,
      cookedHungerRestoreRatio: 0.52,
      lootQuantity: 1,
      cookDurationMs: 5_000,
      rawDiseaseId: 'chronic-wasting',
      rawDiseaseChance: 0.35,
      cookedWellFedBuffId: 'well-fed-fleet-buff',
      cookedWellFedChance: 0.4,
      cookedResidualDiseaseId: 'chronic-wasting',
      cookedResidualDiseaseChance: 0.05,
    },
    {
      speciesId: 'brown-horse',
      rawItemTypeId: 'world-plaza-raw-horse-meat',
      cookedItemTypeId: 'world-plaza-cooked-horse-meat',
      rawDisplayName: 'Raw Horse Meat',
      cookedDisplayName: 'Cooked Horse Meat',
      rawHungerRestoreRatio: 0.28,
      cookedHungerRestoreRatio: 0.54,
      lootQuantity: 1,
      cookDurationMs: 6_000,
      rawDiseaseId: 'equine-drowse',
      rawDiseaseChance: 0.36,
      cookedWellFedBuffId: 'well-fed-endurance-buff',
      cookedWellFedChance: 0.4,
    },
    {
      speciesId: 'work-horse',
      rawItemTypeId: 'world-plaza-raw-work-horse-meat',
      cookedItemTypeId: 'world-plaza-cooked-work-horse-meat',
      rawDisplayName: 'Raw Draft Horse Meat',
      cookedDisplayName: 'Cooked Draft Horse Meat',
      rawHungerRestoreRatio: 0.32,
      cookedHungerRestoreRatio: 0.58,
      lootQuantity: 2,
      cookDurationMs: 7_000,
      rawDiseaseId: 'equine-drowse',
      rawDiseaseChance: 0.36,
      cookedWellFedBuffId: 'well-fed-vigor-buff',
      cookedWellFedChance: 0.38,
    },
    {
      speciesId: 'arabian-horse',
      rawItemTypeId: 'world-plaza-raw-arabian-horse-meat',
      cookedItemTypeId: 'world-plaza-cooked-arabian-horse-meat',
      rawDisplayName: 'Raw Arabian Horse Meat',
      cookedDisplayName: 'Cooked Arabian Horse Meat',
      rawHungerRestoreRatio: 0.26,
      cookedHungerRestoreRatio: 0.52,
      lootQuantity: 1,
      cookDurationMs: 5_500,
      rawDiseaseId: 'equine-drowse',
      rawDiseaseChance: 0.36,
      cookedWellFedBuffId: 'well-fed-fleet-buff',
      cookedWellFedChance: 0.42,
    },
    {
      speciesId: 'donkey',
      rawItemTypeId: 'world-plaza-raw-donkey-meat',
      cookedItemTypeId: 'world-plaza-cooked-donkey-meat',
      rawDisplayName: 'Raw Donkey Meat',
      cookedDisplayName: 'Cooked Donkey Meat',
      rawHungerRestoreRatio: 0.24,
      cookedHungerRestoreRatio: 0.48,
      lootQuantity: 1,
      cookDurationMs: 5_000,
      rawDiseaseId: 'equine-drowse',
      rawDiseaseChance: 0.34,
      cookedWellFedBuffId: 'well-fed-comfort-buff',
      cookedWellFedChance: 0.36,
    },
    {
      speciesId: 'hippo',
      rawItemTypeId: 'world-plaza-raw-hippo-meat',
      cookedItemTypeId: 'world-plaza-cooked-hippo-meat',
      rawDisplayName: 'Raw Hippo Meat',
      cookedDisplayName: 'Cooked Hippo Meat',
      rawHungerRestoreRatio: 0.4,
      cookedHungerRestoreRatio: 0.7,
      lootQuantity: 2,
      cookDurationMs: 10_500,
      rawDiseaseId: 'vibrio-infection',
      rawDiseaseChance: 0.42,
      cookedWellFedBuffId: 'well-fed-hearty-buff',
      cookedWellFedChance: 0.44,
    },
    {
      speciesId: 'water-buffalo',
      rawItemTypeId: 'world-plaza-raw-buffalo-meat',
      cookedItemTypeId: 'world-plaza-cooked-buffalo-meat',
      rawDisplayName: 'Raw Buffalo Meat',
      cookedDisplayName: 'Cooked Buffalo Meat',
      rawHungerRestoreRatio: 0.34,
      cookedHungerRestoreRatio: 0.62,
      lootQuantity: 2,
      cookDurationMs: 8_500,
      rawDiseaseId: 'mad-cow',
      rawDiseaseChance: 0.3,
      cookedWellFedBuffId: 'well-fed-vigor-buff',
      cookedWellFedChance: 0.4,
      cookedResidualDiseaseId: 'mad-cow',
      cookedResidualDiseaseChance: 0.03,
    },
    {
      speciesId: 'turtle',
      rawItemTypeId: 'world-plaza-raw-turtle-meat',
      cookedItemTypeId: 'world-plaza-cooked-turtle-meat',
      rawDisplayName: 'Raw Turtle Meat',
      cookedDisplayName: 'Cooked Turtle Meat',
      rawHungerRestoreRatio: 0.16,
      cookedHungerRestoreRatio: 0.36,
      lootQuantity: 1,
      cookDurationMs: 3_500,
      rawDiseaseId: 'salmonellosis',
      rawDiseaseChance: 0.48,
      cookedWellFedBuffId: 'well-fed-reptile-buff',
      cookedWellFedChance: 0.38,
    },
    {
      speciesId: 'tortoise',
      rawItemTypeId: 'world-plaza-raw-tortoise-meat',
      cookedItemTypeId: 'world-plaza-cooked-tortoise-meat',
      rawDisplayName: 'Raw Tortoise Meat',
      cookedDisplayName: 'Cooked Tortoise Meat',
      rawHungerRestoreRatio: 0.18,
      cookedHungerRestoreRatio: 0.4,
      lootQuantity: 1,
      cookDurationMs: 4_000,
      rawDiseaseId: 'salmonellosis',
      rawDiseaseChance: 0.48,
      cookedWellFedBuffId: 'well-fed-reptile-buff',
      cookedWellFedChance: 0.38,
    },
    {
      speciesId: 'pinguin',
      rawItemTypeId: 'world-plaza-raw-pinguin-meat',
      cookedItemTypeId: 'world-plaza-cooked-pinguin-meat',
      rawDisplayName: 'Raw Pinguin Meat',
      cookedDisplayName: 'Cooked Pinguin Meat',
      rawHungerRestoreRatio: 0.14,
      cookedHungerRestoreRatio: 0.34,
      lootQuantity: 1,
      cookDurationMs: 2_800,
      rawDiseaseId: 'salmonellosis',
      rawDiseaseChance: 0.44,
      cookedWellFedBuffId: 'well-fed-comfort-buff',
      cookedWellFedChance: 0.36,
    },
    {
      speciesId: 'polar-bear',
      rawItemTypeId: 'world-plaza-raw-polar-bear-meat',
      cookedItemTypeId: 'world-plaza-cooked-polar-bear-meat',
      rawDisplayName: 'Raw Polar Bear Meat',
      cookedDisplayName: 'Cooked Polar Bear Meat',
      rawHungerRestoreRatio: 0.38,
      cookedHungerRestoreRatio: 0.68,
      lootQuantity: 1,
      cookDurationMs: 10_000,
      rawDiseaseId: 'bear-worm',
      rawDiseaseChance: 0.5,
      cookedWellFedBuffId: 'well-fed-hearty-buff',
      cookedWellFedChance: 0.44,
    },
    {
      speciesId: 'mammoth',
      rawItemTypeId: 'world-plaza-raw-mammoth-meat',
      cookedItemTypeId: 'world-plaza-cooked-mammoth-meat',
      rawDisplayName: 'Raw Mammoth Meat',
      cookedDisplayName: 'Cooked Mammoth Meat',
      rawHungerRestoreRatio: 0.44,
      cookedHungerRestoreRatio: 0.74,
      lootQuantity: 3,
      cookDurationMs: 12_000,
      rawDiseaseId: 'tusk-fluke',
      rawDiseaseChance: 0.34,
      cookedWellFedBuffId: 'well-fed-hearty-buff',
      cookedWellFedChance: 0.46,
    },
    {
      speciesId: 'camel',
      rawItemTypeId: 'world-plaza-raw-camel-meat',
      cookedItemTypeId: 'world-plaza-cooked-camel-meat',
      rawDisplayName: 'Raw Camel Meat',
      cookedDisplayName: 'Cooked Camel Meat',
      rawHungerRestoreRatio: 0.3,
      cookedHungerRestoreRatio: 0.56,
      lootQuantity: 1,
      cookDurationMs: 6_500,
      rawDiseaseId: 'liver-fluke',
      rawDiseaseChance: 0.34,
      cookedWellFedBuffId: 'well-fed-endurance-buff',
      cookedWellFedChance: 0.4,
    },
    {
      speciesId: 'ram',
      rawItemTypeId: 'world-plaza-raw-ram-mutton',
      cookedItemTypeId: 'world-plaza-cooked-ram-mutton',
      rawDisplayName: 'Raw Ram Mutton',
      cookedDisplayName: 'Cooked Ram Mutton',
      rawHungerRestoreRatio: 0.26,
      cookedHungerRestoreRatio: 0.5,
      lootQuantity: 1,
      cookDurationMs: 5_500,
      rawDiseaseId: 'liver-fluke',
      rawDiseaseChance: 0.36,
      cookedWellFedBuffId: 'well-fed-toughened-buff',
      cookedWellFedChance: 0.38,
    },
    {
      speciesId: 'llama',
      rawItemTypeId: 'world-plaza-raw-llama-meat',
      cookedItemTypeId: 'world-plaza-cooked-llama-meat',
      rawDisplayName: 'Raw Llama Meat',
      cookedDisplayName: 'Cooked Llama Meat',
      rawHungerRestoreRatio: 0.24,
      cookedHungerRestoreRatio: 0.48,
      lootQuantity: 1,
      cookDurationMs: 5_000,
      rawDiseaseId: 'toxoplasmosis',
      rawDiseaseChance: 0.34,
      cookedWellFedBuffId: 'well-fed-comfort-buff',
      cookedWellFedChance: 0.36,
    },
    {
      speciesId: 'alpaca',
      rawItemTypeId: 'world-plaza-raw-alpaca-meat',
      cookedItemTypeId: 'world-plaza-cooked-alpaca-meat',
      rawDisplayName: 'Raw Alpaca Meat',
      cookedDisplayName: 'Cooked Alpaca Meat',
      rawHungerRestoreRatio: 0.22,
      cookedHungerRestoreRatio: 0.44,
      lootQuantity: 1,
      cookDurationMs: 4_500,
      rawDiseaseId: 'toxoplasmosis',
      rawDiseaseChance: 0.32,
      cookedWellFedBuffId: 'well-fed-comfort-buff',
      cookedWellFedChance: 0.38,
    },
    {
      speciesId: 'yak',
      rawItemTypeId: 'world-plaza-raw-yak-meat',
      cookedItemTypeId: 'world-plaza-cooked-yak-meat',
      rawDisplayName: 'Raw Yak Meat',
      cookedDisplayName: 'Cooked Yak Meat',
      rawHungerRestoreRatio: 0.34,
      cookedHungerRestoreRatio: 0.62,
      lootQuantity: 2,
      cookDurationMs: 8_500,
      rawDiseaseId: 'mad-cow',
      rawDiseaseChance: 0.3,
      cookedWellFedBuffId: 'well-fed-hearty-buff',
      cookedWellFedChance: 0.4,
      cookedResidualDiseaseId: 'mad-cow',
      cookedResidualDiseaseChance: 0.03,
    },
    {
      speciesId: 'tiger',
      rawItemTypeId: 'world-plaza-raw-tiger-meat',
      cookedItemTypeId: 'world-plaza-cooked-tiger-meat',
      rawDisplayName: 'Raw Tiger Meat',
      cookedDisplayName: 'Cooked Tiger Meat',
      rawHungerRestoreRatio: 0.3,
      cookedHungerRestoreRatio: 0.58,
      lootQuantity: 1,
      cookDurationMs: 7_500,
      rawDiseaseId: 'toxoplasmosis',
      rawDiseaseChance: 0.38,
      cookedWellFedBuffId: 'well-fed-strength-buff',
      cookedWellFedChance: 0.4,
    },
    {
      speciesId: 'jaguar',
      rawItemTypeId: 'world-plaza-raw-jaguar-meat',
      cookedItemTypeId: 'world-plaza-cooked-jaguar-meat',
      rawDisplayName: 'Raw Jaguar Meat',
      cookedDisplayName: 'Cooked Jaguar Meat',
      rawHungerRestoreRatio: 0.26,
      cookedHungerRestoreRatio: 0.54,
      lootQuantity: 1,
      cookDurationMs: 6_500,
      rawDiseaseId: 'toxoplasmosis',
      rawDiseaseChance: 0.38,
      cookedWellFedBuffId: 'well-fed-strength-buff',
      cookedWellFedChance: 0.38,
    },
    {
      speciesId: 'monkey',
      rawItemTypeId: 'world-plaza-raw-monkey-meat',
      cookedItemTypeId: 'world-plaza-cooked-monkey-meat',
      rawDisplayName: 'Raw Monkey Meat',
      cookedDisplayName: 'Cooked Monkey Meat',
      rawHungerRestoreRatio: 0.1,
      cookedHungerRestoreRatio: 0.26,
      lootQuantity: 1,
      cookDurationMs: 2_500,
      rawDiseaseId: 'primate-fever',
      rawDiseaseChance: 0.42,
      cookedWellFedBuffId: 'well-fed-comfort-buff',
      cookedWellFedChance: 0.32,
    },
    {
      speciesId: 'chimp',
      rawItemTypeId: 'world-plaza-raw-chimp-meat',
      cookedItemTypeId: 'world-plaza-cooked-chimp-meat',
      rawDisplayName: 'Raw Chimp Meat',
      cookedDisplayName: 'Cooked Chimp Meat',
      rawHungerRestoreRatio: 0.18,
      cookedHungerRestoreRatio: 0.4,
      lootQuantity: 1,
      cookDurationMs: 4_500,
      rawDiseaseId: 'primate-fever',
      rawDiseaseChance: 0.44,
      cookedWellFedBuffId: 'well-fed-vigor-buff',
      cookedWellFedChance: 0.34,
    },
    {
      speciesId: 'fairy',
      rawItemTypeId: 'world-plaza-raw-fairy-dust',
      cookedItemTypeId: 'world-plaza-cooked-fairy-dust',
      rawDisplayName: 'Raw Fairy Dust',
      cookedDisplayName: 'Cooked Fairy Dust',
      rawHungerRestoreRatio: 0.04,
      cookedHungerRestoreRatio: 0.1,
      lootQuantity: 1,
      cookDurationMs: 1_500,
      rawDiseaseId: 'salmonellosis',
      rawDiseaseChance: 0.15,
      cookedWellFedBuffId: 'well-fed-comfort-buff',
      cookedWellFedChance: 0.55,
    },
  ];

const DEFINING_WILDLIFE_MEAT_BY_SPECIES = Object.fromEntries(
  DEFINING_WILDLIFE_MEAT_CATALOG.map((entry) => [entry.speciesId, entry])
) as Record<DefiningWildlifeSpeciesId, DefiningWildlifeMeatCatalogEntry>;

const DEFINING_WILDLIFE_ALL_MEAT_CATALOG: readonly DefiningWildlifeMeatCatalogEntry[] =
  [
    ...DEFINING_WILDLIFE_MEAT_CATALOG,
    ...DEFINING_WILDLIFE_VARIANT_MEAT_CATALOG,
  ];

const DEFINING_WILDLIFE_RAW_MEAT_ITEM_TYPE_IDS = new Set(
  DEFINING_WILDLIFE_ALL_MEAT_CATALOG.map((entry) => entry.rawItemTypeId)
);

const DEFINING_WILDLIFE_MEAT_BY_RAW_ITEM_TYPE_ID = Object.fromEntries(
  DEFINING_WILDLIFE_ALL_MEAT_CATALOG.map((entry) => [
    entry.rawItemTypeId,
    entry,
  ])
) as Record<string, DefiningWildlifeMeatCatalogEntry>;

const DEFINING_WILDLIFE_MEAT_BY_COOKED_ITEM_TYPE_ID = Object.fromEntries(
  DEFINING_WILDLIFE_ALL_MEAT_CATALOG.map((entry) => [
    entry.cookedItemTypeId,
    entry,
  ])
) as Record<string, DefiningWildlifeMeatCatalogEntry>;

/** Resolves meat catalog entry for one species. */
export function resolvingWildlifeMeatCatalogEntry(
  speciesId: DefiningWildlifeSpeciesId
): DefiningWildlifeMeatCatalogEntry | null {
  return DEFINING_WILDLIFE_MEAT_BY_SPECIES[speciesId] ?? null;
}

/** Resolves meat catalog entry from a raw or cooked item type id. */
export function resolvingWildlifeMeatCatalogEntryByItemTypeId(
  itemTypeId: string
): DefiningWildlifeMeatCatalogEntry | null {
  return (
    DEFINING_WILDLIFE_MEAT_BY_RAW_ITEM_TYPE_ID[itemTypeId] ??
    DEFINING_WILDLIFE_MEAT_BY_COOKED_ITEM_TYPE_ID[itemTypeId] ??
    null
  );
}

/** Whether an inventory item type id is any wildlife raw meat. */
export function checkingWildlifeRawMeatItemTypeId(itemTypeId: string): boolean {
  return DEFINING_WILDLIFE_RAW_MEAT_ITEM_TYPE_IDS.has(itemTypeId);
}

/** Lists raw meat item type ids present in an inventory slot list. */
export function listingWildlifeRawMeatItemTypeIdsInInventory(
  slots: readonly { itemTypeId: string; quantity: number }[]
): readonly string[] {
  const found: string[] = [];

  for (const slot of slots) {
    if (
      slot.quantity > 0 &&
      checkingWildlifeRawMeatItemTypeId(slot.itemTypeId)
    ) {
      found.push(slot.itemTypeId);
    }
  }

  return found;
}
