import type { DefiningWorldPlazaInventorySpriteSheetIcon } from '@/components/world/inventory/domains/definingWorldPlazaInventoryItemTypeDefinition';
import {
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_BILBERRY,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_BLACKBERRY,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_CRANBERRY,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_JUNIPER,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_LOTUS_FRUIT,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_RASPBERRY,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_SEA_BUCKTHORN,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_WOLFBERRY,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_YEW_ARIL,
} from '@/components/world/inventory/domains/definingWorldPlazaInventoryItemTypeIds';

/**
 * Extended berry inventory sprite sheet (3×3 @ 32px).
 *
 * @module components/world/inventory/domains/definingWorldPlazaInventoryExtendedBerrySpriteSheetConstants
 */

export const DEFINING_WORLD_PLAZA_INVENTORY_EXTENDED_BERRY_SPRITE_SHEET_URL =
  '/inventory/sprites/inventory-extended-berry-sprites.webp' as const;

export const DEFINING_WORLD_PLAZA_INVENTORY_EXTENDED_BERRY_SPRITE_SHEET_COLUMN_COUNT = 3;
export const DEFINING_WORLD_PLAZA_INVENTORY_EXTENDED_BERRY_SPRITE_SHEET_ROW_COUNT = 3;

export const DEFINING_WORLD_PLAZA_INVENTORY_EXTENDED_BERRY_SPRITE_SHEET_TYPE_IDS =
  [
    DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_CRANBERRY,
    DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_BLACKBERRY,
    DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_RASPBERRY,
    DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_BILBERRY,
    DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_JUNIPER,
    DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_SEA_BUCKTHORN,
    DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_YEW_ARIL,
    DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_WOLFBERRY,
    DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_LOTUS_FRUIT,
  ] as const;

const DEFINING_WORLD_PLAZA_INVENTORY_EXTENDED_BERRY_SPRITE_INDEX_BY_TYPE_ID =
  new Map<string, number>(
    DEFINING_WORLD_PLAZA_INVENTORY_EXTENDED_BERRY_SPRITE_SHEET_TYPE_IDS.map(
      (typeId, index) => [typeId, index]
    )
  );

export function resolvingWorldPlazaInventoryExtendedBerrySpriteSheetIcon(
  itemTypeId: string
): DefiningWorldPlazaInventorySpriteSheetIcon | null {
  const sheetIndex =
    DEFINING_WORLD_PLAZA_INVENTORY_EXTENDED_BERRY_SPRITE_INDEX_BY_TYPE_ID.get(
      itemTypeId
    );

  if (sheetIndex === undefined) {
    return null;
  }

  const columnIndex =
    sheetIndex %
    DEFINING_WORLD_PLAZA_INVENTORY_EXTENDED_BERRY_SPRITE_SHEET_COLUMN_COUNT;
  const rowIndex = Math.floor(
    sheetIndex /
      DEFINING_WORLD_PLAZA_INVENTORY_EXTENDED_BERRY_SPRITE_SHEET_COLUMN_COUNT
  );

  return {
    spriteSheetUrl:
      DEFINING_WORLD_PLAZA_INVENTORY_EXTENDED_BERRY_SPRITE_SHEET_URL,
    columnCount:
      DEFINING_WORLD_PLAZA_INVENTORY_EXTENDED_BERRY_SPRITE_SHEET_COLUMN_COUNT,
    rowCount:
      DEFINING_WORLD_PLAZA_INVENTORY_EXTENDED_BERRY_SPRITE_SHEET_ROW_COUNT,
    columnIndex,
    rowIndex,
  };
}
