/**
 * Maps shrub loot kinds to inventory item type ids.
 *
 * @module components/world/inventory/domains/definingWorldPlazaForageLootKindMapping
 */

import {
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_BILBERRY,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_BLACKBERRY,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_BLUE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_CRANBERRY,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_GOLDEN,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_JUNIPER,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_LOTUS_FRUIT,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_RASPBERRY,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_RED,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_SEA_BUCKTHORN,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_WOLFBERRY,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_YEW_ARIL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_BAY_LAUREL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_HOLLY,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_LEMON_BALM,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_MISTLETOE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_MOLY,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_MUGWORT,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_NETTLE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_OLIVE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_SAGE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_TEA_LEAVES,
} from '@/components/world/inventory/domains/definingWorldPlazaInventoryItemTypeIds';
import type { WorldShrubBerryLootKind } from '../../../../shared/worldShrubBerryLoot';

export const DEFINING_WORLD_PLAZA_FORAGE_LOOT_KIND_TO_ITEM_TYPE_ID: Record<
  WorldShrubBerryLootKind,
  string
> = {
  red_berry: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_RED,
  blue_berry: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_BLUE,
  golden_berry: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_GOLDEN,
  tea_leaves: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_TEA_LEAVES,
  cranberry: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_CRANBERRY,
  blackberry: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_BLACKBERRY,
  raspberry: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_RASPBERRY,
  bilberry: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_BILBERRY,
  juniper_berry: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_JUNIPER,
  sea_buckthorn: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_SEA_BUCKTHORN,
  yew_aril: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_YEW_ARIL,
  wolfberry: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_WOLFBERRY,
  lotus_fruit: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_LOTUS_FRUIT,
  nettle: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_NETTLE,
  lemon_balm: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_LEMON_BALM,
  sage: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_SAGE,
  mugwort: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_MUGWORT,
  bay_laurel: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_BAY_LAUREL,
  holly_leaf: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_HOLLY,
  mistletoe: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_MISTLETOE,
  olive_leaf: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_OLIVE,
  moly: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_MOLY,
};

export function resolvingWorldPlazaForageItemTypeIdFromLootKind(
  lootKind: WorldShrubBerryLootKind
): string {
  return DEFINING_WORLD_PLAZA_FORAGE_LOOT_KIND_TO_ITEM_TYPE_ID[lootKind];
}

/** Leaf loot kinds for herbarium Leaves tab filtering. */
export const DEFINING_WORLD_PLAZA_FORAGE_LEAF_LOOT_KINDS = [
  'tea_leaves',
  'nettle',
  'lemon_balm',
  'sage',
  'mugwort',
  'bay_laurel',
  'holly_leaf',
  'mistletoe',
  'olive_leaf',
  'moly',
] as const satisfies readonly WorldShrubBerryLootKind[];

export function checkingWorldPlazaForageLootKindIsLeaf(
  lootKind: WorldShrubBerryLootKind
): boolean {
  return (
    DEFINING_WORLD_PLAZA_FORAGE_LEAF_LOOT_KINDS as readonly string[]
  ).includes(lootKind);
}
