import type { DefiningWorldPlazaInventorySpriteSheetIcon } from '@/components/world/inventory/domains/definingWorldPlazaInventoryItemTypeDefinition';
import {
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_BAY_LAUREL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_HOLLY,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_LEMON_BALM,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_MISTLETOE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_MOLY,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_MUGWORT,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_NETTLE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_OLIVE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_SAGE,
} from '@/components/world/inventory/domains/definingWorldPlazaInventoryItemTypeIds';

/**
 * Extended leaf inventory sprite sheet (3×3 @ 32px).
 *
 * @module components/world/inventory/domains/definingWorldPlazaInventoryExtendedLeafSpriteSheetConstants
 */

export const DEFINING_WORLD_PLAZA_INVENTORY_EXTENDED_LEAF_SPRITE_SHEET_URL =
  '/inventory/sprites/inventory-extended-leaf-sprites.webp' as const;

export const DEFINING_WORLD_PLAZA_INVENTORY_EXTENDED_LEAF_SPRITE_SHEET_COLUMN_COUNT = 3;
export const DEFINING_WORLD_PLAZA_INVENTORY_EXTENDED_LEAF_SPRITE_SHEET_ROW_COUNT = 3;

export const DEFINING_WORLD_PLAZA_INVENTORY_EXTENDED_LEAF_SPRITE_SHEET_TYPE_IDS =
  [
    DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_NETTLE,
    DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_LEMON_BALM,
    DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_SAGE,
    DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_MUGWORT,
    DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_BAY_LAUREL,
    DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_HOLLY,
    DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_MISTLETOE,
    DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_OLIVE,
    DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LEAF_MOLY,
  ] as const;

const DEFINING_WORLD_PLAZA_INVENTORY_EXTENDED_LEAF_SPRITE_INDEX_BY_TYPE_ID =
  new Map<string, number>(
    DEFINING_WORLD_PLAZA_INVENTORY_EXTENDED_LEAF_SPRITE_SHEET_TYPE_IDS.map(
      (typeId, index) => [typeId, index]
    )
  );

export function resolvingWorldPlazaInventoryExtendedLeafSpriteSheetIcon(
  itemTypeId: string
): DefiningWorldPlazaInventorySpriteSheetIcon | null {
  const sheetIndex =
    DEFINING_WORLD_PLAZA_INVENTORY_EXTENDED_LEAF_SPRITE_INDEX_BY_TYPE_ID.get(
      itemTypeId
    );

  if (sheetIndex === undefined) {
    return null;
  }

  const columnIndex =
    sheetIndex %
    DEFINING_WORLD_PLAZA_INVENTORY_EXTENDED_LEAF_SPRITE_SHEET_COLUMN_COUNT;
  const rowIndex = Math.floor(
    sheetIndex /
      DEFINING_WORLD_PLAZA_INVENTORY_EXTENDED_LEAF_SPRITE_SHEET_COLUMN_COUNT
  );

  return {
    spriteSheetUrl:
      DEFINING_WORLD_PLAZA_INVENTORY_EXTENDED_LEAF_SPRITE_SHEET_URL,
    columnCount:
      DEFINING_WORLD_PLAZA_INVENTORY_EXTENDED_LEAF_SPRITE_SHEET_COLUMN_COUNT,
    rowCount:
      DEFINING_WORLD_PLAZA_INVENTORY_EXTENDED_LEAF_SPRITE_SHEET_ROW_COUNT,
    columnIndex,
    rowIndex,
  };
}
