/**
 * Item weight and ground-pickup channel duration band.
 *
 * Weight is a unitless carry cost. Pickup channel duration maps the lightest
 * items to 0.5s and the heaviest to 10s.
 *
 * @module components/world/inventory/domains/definingWorldPlazaInventoryItemWeightConstants
 */

import { DEFINING_WORLD_PLAZA_CRAFTABLE_PLATE_ARMOR_ITEM_TYPE_IDS } from '@/components/world/equipment/domains/definingWorldPlazaCraftablePlateArmorSetRegistry';
import {
  DEFINING_WORLD_PLAZA_EARLY_UNIQUE_WEAPON_ITEM_TYPE_IDS,
  DEFINING_WORLD_PLAZA_INVENTORY_BESSEMER_ARMOR_ITEM_TYPE_IDS,
  DEFINING_WORLD_PLAZA_INVENTORY_CHAOS_ARMOR_ITEM_TYPE_IDS,
  DEFINING_WORLD_PLAZA_INVENTORY_GLASS_VEIL_ARMOR_ITEM_TYPE_IDS,
  DEFINING_WORLD_PLAZA_INVENTORY_HEALER_ITEM_TYPE_IDS,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_APPLE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_AXE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_AXE_GOLD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_AXE_IRON,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_AXE_STEEL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRIES,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_BLUE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_GOLDEN,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_RED,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BOWL_OF_PORRIDGE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BREWED_CLAY_TEAPOT,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BREWED_COFFEE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_COCONUT,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_COFFEE_BEANS,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_COOKED_COCONUT,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_CUP_OF_TEA,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_EMPTY_CLAY_BOTTLE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_EMPTY_CLAY_BOWL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_EMPTY_CLAY_CROCK,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_EMPTY_CLAY_CUP,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_EMPTY_CLAY_TEAPOT,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_EXPEDITION_BAG,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FISH,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FISHROD_GOLD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FISHROD_IRON,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FISHROD_STEEL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FISHROD_WOOD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLINT,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLOWER_ARNICA,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLOWER_BELLADONNA,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLOWER_CALENDULA,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLOWER_CHAMOMILE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLOWER_ECHINACEA,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLOWER_FOXGLOVE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLOWER_LAVENDER,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLOWER_MEADOWSWEET,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLOWER_PEPPERMINT,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLOWER_ROSE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLOWER_VALERIAN,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLOWER_YARROW,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_HOE_GOLD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_HOE_IRON,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_HOE_STEEL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_HOE_WOOD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_INGOT_COPPER,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_INGOT_GOLD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_INGOT_IRON,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_INGOT_LEAD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_INGOT_SILVER,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_INGOT_STEEL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_IRON_TUBE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_MERCURY,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_ORE_CLAY,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_ORE_COAL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_ORE_COPPER,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_ORE_GOLD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_ORE_IRON,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_ORE_LEAD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_ORE_NITER,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_ORE_SCARLET,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_ORE_SILVER,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_ORE_SULFUR,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_PACK,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_PICKAXE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_PICKAXE_GOLD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_PICKAXE_IRON,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_PICKAXE_STEEL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_POUCH,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_RUCKSACK,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SATCHEL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SCYTHE_GOLD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SCYTHE_IRON,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SCYTHE_STEEL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SCYTHE_WOOD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SMOKE_OIL_CROCK,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE_BRIGHT,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE_BRIGHT_CRIMSON,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE_BRIGHT_GOLD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE_FAINT,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE_FAINT_CRIMSON,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE_FAINT_GOLD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE_RADIANT,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE_RADIANT_CRIMSON,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE_RADIANT_GOLD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE_STRONG,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE_STRONG_CRIMSON,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE_STRONG_GOLD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_STONE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SWORD_GOLD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SWORD_IRON,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SWORD_STEEL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SWORD_WOOD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_TEA_LEAVES,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_TOOL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WATERED_CLAY_BOTTLE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WATERED_CLAY_TEAPOT,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WET_CLAY,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WET_CLAY_BOTTLE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WET_CLAY_BOWL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WET_CLAY_CROCK,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WET_CLAY_CUP,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WET_CLAY_TEAPOT,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WHEAT,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WHEAT_SEED,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WOOD,
  DEFINING_WORLD_PLAZA_INVENTORY_SURVIVAL_ITEM_TYPE_IDS,
  DEFINING_WORLD_PLAZA_LATE_UNIQUE_WEAPON_ITEM_TYPE_IDS,
  DEFINING_WORLD_PLAZA_MID_UNIQUE_WEAPON_ITEM_TYPE_IDS,
} from '@/components/world/inventory/domains/definingWorldPlazaInventoryItemTypeIds';

/** Lightest carry weight (berries, seeds, spritcore). */
export const DEFINING_WORLD_PLAZA_INVENTORY_ITEM_WEIGHT_MIN = 0.5 as const;

/** Heaviest carry weight (megafauna meat, expedition bag). */
export const DEFINING_WORLD_PLAZA_INVENTORY_ITEM_WEIGHT_MAX = 100 as const;

/** Fallback when an item type has no explicit weight. */
export const DEFINING_WORLD_PLAZA_INVENTORY_ITEM_WEIGHT_DEFAULT = 1 as const;

/** Shortest ground-pickup channel (lightest items), ms. */
export const DEFINING_WORLD_PLAZA_GROUND_ITEM_PICKUP_DURATION_MIN_MS =
  500 as const;

/** Longest ground-pickup channel (heaviest items), ms. */
export const DEFINING_WORLD_PLAZA_GROUND_ITEM_PICKUP_DURATION_MAX_MS =
  10_000 as const;

/**
 * Species mass (kg) at or below this maps meat pickup weight to the minimum.
 * Matches chicken-scale animals in the wildlife registry.
 */
export const DEFINING_WORLD_PLAZA_MEAT_PICKUP_WEIGHT_MASS_MIN_KG = 3 as const;

/**
 * Species mass (kg) at or above this maps meat pickup weight to the maximum.
 * Matches elephant-scale megafauna.
 */
export const DEFINING_WORLD_PLAZA_MEAT_PICKUP_WEIGHT_MASS_MAX_KG =
  5_000 as const;

/** Explicit weights for non-meat plaza item type ids. */
export const DEFINING_WORLD_PLAZA_INVENTORY_ITEM_WEIGHT_BY_TYPE_ID: Readonly<
  Record<string, number>
> = {
  ...Object.fromEntries(
    DEFINING_WORLD_PLAZA_INVENTORY_HEALER_ITEM_TYPE_IDS.map((typeId) => [
      typeId,
      1.25,
    ])
  ),
  ...Object.fromEntries(
    DEFINING_WORLD_PLAZA_INVENTORY_SURVIVAL_ITEM_TYPE_IDS.map((typeId) => [
      typeId,
      typeId.includes('survival-hide') ||
      typeId.includes('survival-fur') ||
      typeId.includes('survival-adobe') ||
      typeId.includes('survival-split-planks')
        ? 2.5
        : typeId.includes('boots') ||
            typeId.includes('cape') ||
            typeId.includes('poncho') ||
            typeId.includes('vest')
          ? 2
          : typeId.includes('rope') ||
              typeId.includes('twine') ||
              typeId.includes('peg-stake')
            ? 1.5
            : 1.25,
    ])
  ),
  ...Object.fromEntries(
    DEFINING_WORLD_PLAZA_INVENTORY_CHAOS_ARMOR_ITEM_TYPE_IDS.map((typeId) => [
      typeId,
      typeId.includes('cuirass') ? 4 : typeId.includes('greaves') ? 3.5 : 3,
    ])
  ),
  ...Object.fromEntries(
    DEFINING_WORLD_PLAZA_INVENTORY_BESSEMER_ARMOR_ITEM_TYPE_IDS.map(
      (typeId) => [
        typeId,
        typeId.includes('breastplate')
          ? 4.5
          : typeId.includes('greaves')
            ? 4
            : 3.5,
      ]
    )
  ),
  ...Object.fromEntries(
    DEFINING_WORLD_PLAZA_CRAFTABLE_PLATE_ARMOR_ITEM_TYPE_IDS.map((typeId) => [
      typeId,
      typeId.includes('leather-plate')
        ? typeId.includes('breastplate')
          ? 2.5
          : 2
        : typeId.includes('gold-plate')
          ? typeId.includes('breastplate')
            ? 4.5
            : typeId.includes('greaves')
              ? 4
              : 3.5
          : typeId.includes('breastplate')
            ? 4
            : typeId.includes('greaves')
              ? 3.5
              : 3,
    ])
  ),
  ...Object.fromEntries(
    DEFINING_WORLD_PLAZA_INVENTORY_GLASS_VEIL_ARMOR_ITEM_TYPE_IDS.map(
      (typeId) => [
        typeId,
        typeId.includes('mantle') ? 2 : typeId.includes('greaves') ? 1.75 : 1.5,
      ]
    )
  ),
  ...Object.fromEntries(
    DEFINING_WORLD_PLAZA_EARLY_UNIQUE_WEAPON_ITEM_TYPE_IDS.map((typeId) => [
      typeId,
      2.5,
    ])
  ),
  ...Object.fromEntries(
    DEFINING_WORLD_PLAZA_MID_UNIQUE_WEAPON_ITEM_TYPE_IDS.map((typeId) => [
      typeId,
      3.0,
    ])
  ),
  ...Object.fromEntries(
    DEFINING_WORLD_PLAZA_LATE_UNIQUE_WEAPON_ITEM_TYPE_IDS.map((typeId) => [
      typeId,
      3.5,
    ])
  ),
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRIES]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_RED]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_BLUE]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRY_GOLDEN]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_TEA_LEAVES]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_COFFEE_BEANS]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BREWED_COFFEE]: 1,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_CUP_OF_TEA]: 1,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_EMPTY_CLAY_CUP]: 0.75,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_EMPTY_CLAY_BOTTLE]: 1.25,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WATERED_CLAY_BOTTLE]: 1.75,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_EMPTY_CLAY_TEAPOT]: 1.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WATERED_CLAY_TEAPOT]: 2,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BREWED_CLAY_TEAPOT]: 2,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WET_CLAY_CUP]: 1,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WET_CLAY_BOTTLE]: 1.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WET_CLAY_TEAPOT]: 2,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WET_CLAY_BOWL]: 1.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_EMPTY_CLAY_BOWL]: 1.25,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BOWL_OF_PORRIDGE]: 1.75,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WET_CLAY_CROCK]: 2.25,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_EMPTY_CLAY_CROCK]: 2,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SMOKE_OIL_CROCK]: 2.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_APPLE]: 0.75,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_COCONUT]: 1.25,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_COOKED_COCONUT]: 1,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WHEAT_SEED]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WHEAT]: 0.75,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FISH]: 1.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WOOD]: 2,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_STONE]: 4,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_ORE_CLAY]: 3,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WET_CLAY]: 3.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_ORE_COAL]: 3.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_ORE_IRON]: 5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_ORE_COPPER]: 4.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_ORE_SILVER]: 5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_ORE_GOLD]: 6,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_ORE_NITER]: 3,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_ORE_SCARLET]: 4.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_ORE_LEAD]: 6.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_ORE_SULFUR]: 3.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_INGOT_IRON]: 4,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_INGOT_COPPER]: 3.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_INGOT_SILVER]: 4,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_INGOT_GOLD]: 5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_INGOT_LEAD]: 5.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_INGOT_STEEL]: 4.25,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_IRON_TUBE]: 8,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_MERCURY]: 4,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLINT]: 1.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE_FAINT]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE_BRIGHT]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE_STRONG]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE_RADIANT]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE_FAINT_CRIMSON]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE_BRIGHT_CRIMSON]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE_STRONG_CRIMSON]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE_RADIANT_CRIMSON]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE_FAINT_GOLD]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE_BRIGHT_GOLD]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE_STRONG_GOLD]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SPRITCORE_RADIANT_GOLD]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_TOOL]: 3,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_AXE]: 4,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SWORD_WOOD]: 3,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SWORD_IRON]: 5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SWORD_STEEL]: 5.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SWORD_GOLD]: 4.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_AXE_IRON]: 5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_AXE_STEEL]: 5.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_AXE_GOLD]: 4.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_PICKAXE]: 4,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_PICKAXE_IRON]: 5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_PICKAXE_STEEL]: 5.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_PICKAXE_GOLD]: 4.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_HOE_WOOD]: 2.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_HOE_IRON]: 4,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_HOE_STEEL]: 4.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_HOE_GOLD]: 3.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SCYTHE_WOOD]: 2.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SCYTHE_IRON]: 4,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SCYTHE_STEEL]: 4.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SCYTHE_GOLD]: 3.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FISHROD_WOOD]: 2,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FISHROD_IRON]: 3,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FISHROD_STEEL]: 3.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FISHROD_GOLD]: 2.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_POUCH]: 1,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SATCHEL]: 3,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_PACK]: 8,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_RUCKSACK]: 20,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_EXPEDITION_BAG]: 45,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLOWER_YARROW]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLOWER_CALENDULA]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLOWER_CHAMOMILE]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLOWER_LAVENDER]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLOWER_ECHINACEA]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLOWER_PEPPERMINT]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLOWER_ROSE]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLOWER_MEADOWSWEET]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLOWER_ARNICA]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLOWER_VALERIAN]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLOWER_FOXGLOVE]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLOWER_BELLADONNA]: 0.5,
};
