export const DEFINING_WORLD_PLAZA_HEALER_EFFECT_PROC_ROLL_ALWAYS = 0;
export const DEFINING_WORLD_PLAZA_HEALER_FOXGLOVE_SUCCESS_CHANCE = 0.7;
export const DEFINING_WORLD_PLAZA_HEALER_GRADED_PURGE_SEVERE_CHANCE = 0.5;
export const DEFINING_WORLD_PLAZA_HEALER_BELLADONNA_PURGE_SUCCESS_CHANCE = 0.65;
export const DEFINING_WORLD_PLAZA_HEALER_DEEP_REST_DISEASE_REMAINING_FACTOR = 0.3;
