/**
 * Tall-grass forage inventory sprite sheet (4×3 @ 32px).
 *
 * @module components/world/inventory/domains/definingWorldPlazaInventoryTallGrassSpriteSheetConstants
 */

import { DEFINING_WORLD_PLAZA_CLOVER_LOOT_KIND_TO_ITEM_TYPE_ID } from '@/components/world/inventory/domains/definingWorldPlazaInventoryCloverSpriteSheetConstants';
import type { DefiningWorldPlazaInventorySpriteSheetIcon } from '@/components/world/inventory/domains/definingWorldPlazaInventoryItemTypeDefinition';
import {
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BURROW_FLUFF,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_CHIRPER_SHELL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_DEW_CAUGHT_SEED,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FIELD_SNAIL_TRAIL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_GRASS_FIBER,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_KNOTWEED_STEM,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LOST_STITCH_SCRAP,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_MEADOW_MITE_HUSK,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_RUSTED_CLASP,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SOFT_DOWN,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_THATCH_BUNDLE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WILD_OAT_HEAD,
} from '@/components/world/inventory/domains/definingWorldPlazaInventoryItemTypeIds';
import {
  checkingWorldLongGrassSearchLootIsClover,
  type WorldLongGrassSearchLootKind,
  type WorldLongGrassSearchMaterialLootKind,
} from '../../../../shared/worldLongGrassSearchLoot';

export const DEFINING_WORLD_PLAZA_INVENTORY_TALL_GRASS_SPRITE_SHEET_URL =
  '/inventory/sprites/inventory-tall-grass-sprites.webp' as const;

export const DEFINING_WORLD_PLAZA_INVENTORY_TALL_GRASS_SPRITE_SHEET_COLUMN_COUNT = 4;
export const DEFINING_WORLD_PLAZA_INVENTORY_TALL_GRASS_SPRITE_SHEET_ROW_COUNT = 3;

/** Sheet order: left→right, top→bottom (matches loot material kinds). */
export const DEFINING_WORLD_PLAZA_INVENTORY_TALL_GRASS_SPRITE_SHEET_TYPE_IDS = [
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_THATCH_BUNDLE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_GRASS_FIBER,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SOFT_DOWN,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_CHIRPER_SHELL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_MEADOW_MITE_HUSK,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WILD_OAT_HEAD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_KNOTWEED_STEM,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_DEW_CAUGHT_SEED,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LOST_STITCH_SCRAP,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FIELD_SNAIL_TRAIL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BURROW_FLUFF,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_RUSTED_CLASP,
] as const;

export const DEFINING_WORLD_PLAZA_TALL_GRASS_MATERIAL_LOOT_KIND_TO_ITEM_TYPE_ID: Record<
  WorldLongGrassSearchMaterialLootKind,
  (typeof DEFINING_WORLD_PLAZA_INVENTORY_TALL_GRASS_SPRITE_SHEET_TYPE_IDS)[number]
> = {
  thatch_bundle: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_THATCH_BUNDLE,
  grass_fiber: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_GRASS_FIBER,
  soft_down: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SOFT_DOWN,
  chirper_shell: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_CHIRPER_SHELL,
  meadow_mite_husk: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_MEADOW_MITE_HUSK,
  wild_oat_head: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WILD_OAT_HEAD,
  knotweed_stem: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_KNOTWEED_STEM,
  dew_caught_seed: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_DEW_CAUGHT_SEED,
  lost_stitch_scrap: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_LOST_STITCH_SCRAP,
  field_snail_trail: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FIELD_SNAIL_TRAIL,
  burrow_fluff: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BURROW_FLUFF,
  rusted_clasp: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_RUSTED_CLASP,
};

const DEFINING_WORLD_PLAZA_INVENTORY_TALL_GRASS_SPRITE_INDEX_BY_TYPE_ID =
  new Map<string, number>(
    DEFINING_WORLD_PLAZA_INVENTORY_TALL_GRASS_SPRITE_SHEET_TYPE_IDS.map(
      (typeId, index) => [typeId, index]
    )
  );

export function resolvingWorldPlazaInventoryTallGrassSpriteSheetIcon(
  itemTypeId: string
): DefiningWorldPlazaInventorySpriteSheetIcon | null {
  const sheetIndex =
    DEFINING_WORLD_PLAZA_INVENTORY_TALL_GRASS_SPRITE_INDEX_BY_TYPE_ID.get(
      itemTypeId
    );

  if (sheetIndex === undefined) {
    return null;
  }

  const columnIndex =
    sheetIndex %
    DEFINING_WORLD_PLAZA_INVENTORY_TALL_GRASS_SPRITE_SHEET_COLUMN_COUNT;
  const rowIndex = Math.floor(
    sheetIndex /
      DEFINING_WORLD_PLAZA_INVENTORY_TALL_GRASS_SPRITE_SHEET_COLUMN_COUNT
  );

  return {
    spriteSheetUrl: DEFINING_WORLD_PLAZA_INVENTORY_TALL_GRASS_SPRITE_SHEET_URL,
    columnCount:
      DEFINING_WORLD_PLAZA_INVENTORY_TALL_GRASS_SPRITE_SHEET_COLUMN_COUNT,
    rowCount: DEFINING_WORLD_PLAZA_INVENTORY_TALL_GRASS_SPRITE_SHEET_ROW_COUNT,
    columnIndex,
    rowIndex,
  };
}

export function resolvingWorldPlazaLongGrassItemTypeIdFromLootKind(
  lootKind: WorldLongGrassSearchLootKind
): string {
  if (checkingWorldLongGrassSearchLootIsClover(lootKind)) {
    return DEFINING_WORLD_PLAZA_CLOVER_LOOT_KIND_TO_ITEM_TYPE_ID[lootKind];
  }

  return DEFINING_WORLD_PLAZA_TALL_GRASS_MATERIAL_LOOT_KIND_TO_ITEM_TYPE_ID[
    lootKind
  ];
}
