/**
 * Item weight and ground-pickup channel duration band.
 *
 * Weight is a unitless carry cost. Pickup channel duration maps the lightest
 * items to 0.5s and the heaviest to 10s.
 *
 * @module components/world/inventory/domains/definingWorldPlazaInventoryItemWeightConstants
 */

import {
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_APPLE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_AXE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_AXE_GOLD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_AXE_IRON,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_AXE_STEEL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_PICKAXE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_PICKAXE_GOLD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_PICKAXE_IRON,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_PICKAXE_STEEL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRIES,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_EXPEDITION_BAG,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FISH,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FISHROD_GOLD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FISHROD_IRON,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FISHROD_STEEL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FISHROD_WOOD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLINT,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_HOE_GOLD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_HOE_IRON,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_HOE_STEEL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_HOE_WOOD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_PACK,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_POUCH,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_RUCKSACK,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SATCHEL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SCYTHE_GOLD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SCYTHE_IRON,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SCYTHE_STEEL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SCYTHE_WOOD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SOULCORE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_STONE,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SWORD_GOLD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SWORD_IRON,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SWORD_STEEL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SWORD_WOOD,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_TOOL,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WHEAT,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WHEAT_SEED,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WOOD,
} from '@/components/world/inventory/domains/definingWorldPlazaInventoryItemTypeIds';

/** Lightest carry weight (berries, seeds, soulcore). */
export const DEFINING_WORLD_PLAZA_INVENTORY_ITEM_WEIGHT_MIN = 0.5 as const;

/** Heaviest carry weight (megafauna meat, expedition bag). */
export const DEFINING_WORLD_PLAZA_INVENTORY_ITEM_WEIGHT_MAX = 100 as const;

/** Fallback when an item type has no explicit weight. */
export const DEFINING_WORLD_PLAZA_INVENTORY_ITEM_WEIGHT_DEFAULT = 1 as const;

/** Shortest ground-pickup channel (lightest items), ms. */
export const DEFINING_WORLD_PLAZA_GROUND_ITEM_PICKUP_DURATION_MIN_MS =
  500 as const;

/** Longest ground-pickup channel (heaviest items), ms. */
export const DEFINING_WORLD_PLAZA_GROUND_ITEM_PICKUP_DURATION_MAX_MS =
  10_000 as const;

/**
 * Species mass (kg) at or below this maps meat pickup weight to the minimum.
 * Matches chicken-scale animals in the wildlife registry.
 */
export const DEFINING_WORLD_PLAZA_MEAT_PICKUP_WEIGHT_MASS_MIN_KG = 3 as const;

/**
 * Species mass (kg) at or above this maps meat pickup weight to the maximum.
 * Matches elephant-scale megafauna.
 */
export const DEFINING_WORLD_PLAZA_MEAT_PICKUP_WEIGHT_MASS_MAX_KG = 5_000 as const;

/** Explicit weights for non-meat plaza item type ids. */
export const DEFINING_WORLD_PLAZA_INVENTORY_ITEM_WEIGHT_BY_TYPE_ID: Readonly<
  Record<string, number>
> = {
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_BERRIES]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_APPLE]: 0.75,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WHEAT_SEED]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WHEAT]: 0.75,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FISH]: 1.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_WOOD]: 2,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_STONE]: 4,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FLINT]: 1.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SOULCORE]: 0.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_TOOL]: 3,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_AXE]: 4,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SWORD_WOOD]: 3,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SWORD_IRON]: 5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SWORD_STEEL]: 5.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SWORD_GOLD]: 4.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_AXE_IRON]: 5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_AXE_STEEL]: 5.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_AXE_GOLD]: 4.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_PICKAXE]: 4,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_PICKAXE_IRON]: 5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_PICKAXE_STEEL]: 5.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_PICKAXE_GOLD]: 4.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_HOE_WOOD]: 2.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_HOE_IRON]: 4,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_HOE_STEEL]: 4.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_HOE_GOLD]: 3.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SCYTHE_WOOD]: 2.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SCYTHE_IRON]: 4,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SCYTHE_STEEL]: 4.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SCYTHE_GOLD]: 3.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FISHROD_WOOD]: 2,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FISHROD_IRON]: 3,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FISHROD_STEEL]: 3.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_FISHROD_GOLD]: 2.5,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_POUCH]: 1,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_SATCHEL]: 3,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_PACK]: 8,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_RUCKSACK]: 20,
  [DEFINING_WORLD_PLAZA_INVENTORY_ITEM_TYPE_EXPEDITION_BAG]: 45,
};
