import {
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_ARMED_BUTTON_CLASS_NAME,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_BUTTON_CLASS_NAME,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_DESTRUCTIVE_BUTTON_CLASS_NAME,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_INFO_BUTTON_CLASS_NAME,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_MOBILE_ARMED_BUTTON_CLASS_NAME,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_MOBILE_BUTTON_CLASS_NAME,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_MOBILE_DESTRUCTIVE_BUTTON_CLASS_NAME,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_MOBILE_INFO_BUTTON_CLASS_NAME,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_MOBILE_PANEL_CLASS_NAME,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_MOBILE_SHELL_CLASS_NAME,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_PANEL_CLASS_NAME,
  DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_SHELL_CLASS_NAME,
} from '@/components/world/inventory/domains/definingWorldPlazaInventoryItemDetailConstants';

/** Resolved class names for one item action tower layout profile. */
export type DefiningWorldPlazaInventoryItemActionTowerClassNames = {
  readonly shell: string;
  readonly panel: string;
  readonly infoButton: string;
  readonly button: string;
  readonly destructiveButton: string;
  readonly armedButton: string;
};

const DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_DESKTOP_CLASS_NAMES: DefiningWorldPlazaInventoryItemActionTowerClassNames =
  {
    shell: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_SHELL_CLASS_NAME,
    panel: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_PANEL_CLASS_NAME,
    infoButton:
      DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_INFO_BUTTON_CLASS_NAME,
    button: DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_BUTTON_CLASS_NAME,
    destructiveButton:
      DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_DESTRUCTIVE_BUTTON_CLASS_NAME,
    armedButton:
      DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_ARMED_BUTTON_CLASS_NAME,
  };

const DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_MOBILE_CLASS_NAMES: DefiningWorldPlazaInventoryItemActionTowerClassNames =
  {
    shell:
      DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_MOBILE_SHELL_CLASS_NAME,
    panel:
      DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_MOBILE_PANEL_CLASS_NAME,
    infoButton:
      DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_MOBILE_INFO_BUTTON_CLASS_NAME,
    button:
      DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_MOBILE_BUTTON_CLASS_NAME,
    destructiveButton:
      DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_MOBILE_DESTRUCTIVE_BUTTON_CLASS_NAME,
    armedButton:
      DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_MOBILE_ARMED_BUTTON_CLASS_NAME,
  };

/**
 * Picks compact desktop or touch-friendly mobile classes for the item action tower.
 *
 * @param isMobile - Whether the plaza HUD is in the mobile viewport profile
 */
export function resolvingWorldPlazaInventoryItemActionTowerClassNames(
  isMobile: boolean
): DefiningWorldPlazaInventoryItemActionTowerClassNames {
  return isMobile
    ? DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_MOBILE_CLASS_NAMES
    : DEFINING_WORLD_PLAZA_INVENTORY_ITEM_ACTION_TOWER_DESKTOP_CLASS_NAMES;
}
